# Generated by Skyramp v1.3.14 on 2026-03-20 18:37:51.38254413 +0000 UTC m=+108.224629357
# Command: skyramp generate contract rest http://localhost:4200/task-retries/budgets \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /task-retries/budgets GET
def test_budgets_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    budgets_GET_response = client.send_request(
        url=URL,
        path="/task-retries/budgets",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(budgets_GET_response, "20x")


if __name__ == "__main__":
    test_budgets_get()
