# Generated by Skyramp v1.3.14 on 2026-03-20 17:30:01.7611813 +0000 UTC m=+105.998942467
# Command: skyramp generate contract rest http://localhost:4200/api/task-retries/budgets \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"flow_id":"flow-test-abc","max_retries":5} \
# 		--response-data {"flow_id":"flow-test-abc","max_retries":5,"used_retries":0,"budget_set":true} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/task-retries/budgets POST
def test_budgets_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    budgets_POST_request_body = r'''{
        "flow_id": "flow-test-abc",
        "max_retries": 5
    }'''

    # Expected Response Body
    expected_budgets_POST_response_body = r'''{
        "budget_set": true,
        "flow_id": "flow-test-abc",
        "max_retries": 5,
        "used_retries": 0
    }'''

    # Execute Request
    budgets_POST_response = client.send_request(
        url=URL,
        path="/api/task-retries/budgets",
        method="POST",
        body=budgets_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(budgets_POST_response, "20x")
    assert skyramp.check_schema(budgets_POST_response, expected_budgets_POST_response_body)
    assert skyramp.get_response_value(budgets_POST_response, "budget_set") is not None
    assert skyramp.get_response_value(budgets_POST_response, "flow_id") is not None
    assert skyramp.get_response_value(budgets_POST_response, "max_retries") is not None


if __name__ == "__main__":
    test_budgets_post()
