# Generated by Skyramp v1.3.14 on 2026-03-20 17:29:58.554253873 +0000 UTC m=+102.792015030
# Command: skyramp generate contract rest http://localhost:4200/api/task-retries/budgets \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-data {"budgets":[{"flow_id":"flow-1","max_retries":10,"used_retries":3},{"flow_id":"flow-2","max_retries":5,"used_retries":5}]} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/task-retries/budgets GET
def test_budgets_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_budgets_GET_response_body = r'''{
        "budgets": [
            {
                "flow_id": "flow-1",
                "max_retries": 10,
                "used_retries": 3
            },
            {
                "flow_id": "flow-2",
                "max_retries": 5,
                "used_retries": 5
            }
        ]
    }'''

    # Execute Request
    budgets_GET_response = client.send_request(
        url=URL,
        path="/api/task-retries/budgets",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(budgets_GET_response, "20x")
    assert skyramp.check_schema(budgets_GET_response, expected_budgets_GET_response_body)
    assert skyramp.get_response_value(budgets_GET_response, "budgets.0.flow_id") is not None
    assert skyramp.get_response_value(budgets_GET_response, "budgets.0.max_retries") is not None
    assert skyramp.get_response_value(budgets_GET_response, "budgets.0.used_retries") is not None


if __name__ == "__main__":
    test_budgets_get()
