# Generated by Skyramp v1.3.14 on 2026-03-22 21:13:37.917834133 +0000 UTC m=+188.890370302
# Command: skyramp generate contract rest http://127.0.0.1:4200/api/checkpoints-v2/checkpoints/{checkpoint_id} \
# 		--api-schema http://127.0.0.1:4200/api/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params checkpoint_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--response-data {"id":"3fa85f64-5717-4562-b3fc-2c963f66afa6","name":"data_transformed","state":"completed","created_at":"2026-03-20T10:00:00","metadata":{"task_count":2,"rows_processed":50000,"memory_usage_mb":256,"cpu_seconds":45},"state_data":{"variables":{"batch_size":1000,"total_batches":50},"task_states":{"extract_data":"completed","transform_data":"completed"}}} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

# contract test for /api/checkpoints-v2/checkpoints/{checkpoint_id} GET
def test_checkpoints_checkpoint_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    checkpoint_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Expected Response Body
    expected_checkpoints_checkpoint_id_GET_response_body = r'''{
        "created_at": "2026-03-20T10:00:00",
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "metadata": {
            "cpu_seconds": 45,
            "memory_usage_mb": 256,
            "rows_processed": 50000,
            "task_count": 2
        },
        "name": "data_transformed",
        "state": "completed",
        "state_data": {
            "task_states": {
                "extract_data": "completed",
                "transform_data": "completed"
            },
            "variables": {
                "batch_size": 1000,
                "total_batches": 50
            }
        }
    }'''

    # Execute Request
    checkpoints_checkpoint_id_GET_response = client.send_request(
        url=URL,
        path="/api/checkpoints-v2/checkpoints/{checkpoint_id}",
        method="GET",
        headers=headers,
        path_params={"checkpoint_id": checkpoint_id}
    )

    # Generated Assertions
    assert checkpoints_checkpoint_id_GET_response.status_code == 200
    assert skyramp.check_schema(checkpoints_checkpoint_id_GET_response, expected_checkpoints_checkpoint_id_GET_response_body)
    assert skyramp.get_response_value(checkpoints_checkpoint_id_GET_response, "created_at") is not None
    assert skyramp.get_response_value(checkpoints_checkpoint_id_GET_response, "id") is not None
    assert skyramp.get_response_value(checkpoints_checkpoint_id_GET_response, "metadata.cpu_seconds") is not None


if __name__ == "__main__":
    test_checkpoints_checkpoint_id_get()
