# Generated by Skyramp v1.3.14 on 2026-03-22 20:12:55.406656279 +0000 UTC m=+126.782308086
# Command: skyramp generate contract rest http://localhost:4200/checkpoints-v2/checkpoints/{checkpoint_id} \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params checkpoint_id=3fa85f64-5717-4562-b3fc-2c963f66afa7 \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /checkpoints-v2/checkpoints/{checkpoint_id} GET
def test_checkpoints_checkpoint_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    checkpoint_id = "3fa85f64-5717-4562-b3fc-2c963f66afa7"

    # Execute Request
    checkpoints_checkpoint_id_GET_response = client.send_request(
        url=URL,
        path="/checkpoints-v2/checkpoints/{checkpoint_id}",
        method="GET",
        headers=headers,
        path_params={"checkpoint_id": checkpoint_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(checkpoints_checkpoint_id_GET_response, "20x")


if __name__ == "__main__":
    test_checkpoints_checkpoint_id_get()
