# Generated by Skyramp v1.3.14 on 2026-03-22 21:19:12.562795942 +0000 UTC m=+155.204878089
# Command: skyramp generate contract rest http://localhost:4200/api/retry-budgets-v2/flows/{flow_id}/retry-budget/ \
# 		--auth-header Authorization \
# 		--consumer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--response-data {"flow_id":"3fa85f64-5717-4562-b3fc-2c963f66afa6","retry_budget":{"max_retries_per_task":3,"max_retries_per_hour":50,"max_retries_per_day":200,"enabled":true},"current_usage":{"retries_this_hour":12,"retries_today":45,"active_retrying_tasks":3},"usage_percentages":{"hourly":24.0,"daily":22.5}} \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp
from skyramp import MockV2


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/retry-budgets-v2/flows/{flow_id}/retry-budget/ GET
def test_retry_budget_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Expected Response Body
    expected_retry_budget_GET_response_body = r'''{
        "current_usage": {
            "active_retrying_tasks": 3,
            "retries_this_hour": 12,
            "retries_today": 45
        },
        "flow_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "retry_budget": {
            "enabled": true,
            "max_retries_per_day": 200,
            "max_retries_per_hour": 50,
            "max_retries_per_task": 3
        },
        "usage_percentages": {
            "daily": 22.5,
            "hourly": 24
        }
    }'''

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/retry-budgets-v2/flows/{flow_id}/retry-budget/",
        method="GET",
        status_code=200,
        response_body=expected_retry_budget_GET_response_body
    )
    client.apply_mock(mock)

    # Execute Request
    retry_budget_GET_response = client.send_request(
        url=URL,
        path="/api/retry-budgets-v2/flows/{flow_id}/retry-budget/",
        method="GET",
        headers=headers,
        path_params={"flow_id": flow_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(retry_budget_GET_response, "20x")
    assert skyramp.check_schema(retry_budget_GET_response, expected_retry_budget_GET_response_body)
    assert skyramp.get_response_value(retry_budget_GET_response, "current_usage.active_retrying_tasks") is not None
    assert skyramp.get_response_value(retry_budget_GET_response, "current_usage.retries_this_hour") is not None
    assert skyramp.get_response_value(retry_budget_GET_response, "current_usage.retries_today") is not None

    client.remove_all_mocks()


if __name__ == "__main__":
    test_retry_budget_get()
