# Generated by Skyramp v1.3.14 on 2026-03-20 18:08:51.018606127 +0000 UTC m=+129.548684429
# Command: skyramp generate contract rest http://localhost:4200/api/traces-v2/flow-runs/{flow_run_id}/trace/ \
# 		--consumer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_run_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp
from skyramp import MockV2


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/traces-v2/flow-runs/{flow_run_id}/trace/ GET
def test_trace_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_run_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/traces-v2/flow-runs/{flow_run_id}/trace/",
        method="GET",
        status_code=200
    )
    client.apply_mock(mock)

    # Execute Request
    trace_GET_response = client.send_request(
        url=URL,
        path="/api/traces-v2/flow-runs/{flow_run_id}/trace/",
        method="GET",
        headers=headers,
        path_params={"flow_run_id": flow_run_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(trace_GET_response, "20x")

    client.remove_all_mocks()


if __name__ == "__main__":
    test_trace_get()
