# Generated by Skyramp v1.3.14 on 2026-03-20 17:53:07.46365458 +0000 UTC m=+181.216146236
# Command: skyramp generate contract rest http://localhost:4200/api/quotas-v2/flows/{flow_id}/quota/ \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method PATCH \
# 		--output contract_quota_update_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--request-data {"max_concurrent_runs":15,"max_daily_runs":150} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/quotas-v2/flows/{flow_id}/quota/ PATCH
def test_quota_patch():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    quota_PATCH_request_body = r'''{
        "max_concurrent_runs": 15,
        "max_daily_runs": 150
    }'''

    # Execute Request
    quota_PATCH_response = client.send_request(
        url=URL,
        path="/api/quotas-v2/flows/{flow_id}/quota/",
        method="PATCH",
        body=quota_PATCH_request_body,
        headers=headers,
        path_params={"flow_id": flow_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(quota_PATCH_response, "20x")


if __name__ == "__main__":
    test_quota_patch()
