# Generated by Skyramp v1.3.14 on 2026-03-20 17:55:04.381346253 +0000 UTC m=+214.960017468
# Command: skyramp generate contract rest http://localhost:4200/api/checkpoints-v2/flow-runs/{flow_run_id}/checkpoints/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_test_get_checkpoints_schema.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_run_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/checkpoints-v2/flow-runs/{flow_run_id}/checkpoints/ GET
def test_checkpoints_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_run_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Execute Request
    checkpoints_GET_response = client.send_request(
        url=URL,
        path="/api/checkpoints-v2/flow-runs/{flow_run_id}/checkpoints/",
        method="GET",
        headers=headers,
        path_params={"flow_run_id": flow_run_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(checkpoints_GET_response, "20x")


if __name__ == "__main__":
    test_checkpoints_get()
