# Generated by Skyramp v1.3.14 on 2026-03-20 17:39:34.867827352 +0000 UTC m=+126.980313509
# Command: skyramp generate contract rest http://localhost:4200/api/impact-v2/flows/{flow_id}/dependencies/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_flow_dependencies_post.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--request-data {"downstream_flows":["flow-b","flow-c"]} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/impact-v2/flows/{flow_id}/dependencies/ POST
def test_dependencies_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    dependencies_POST_request_body = r'''{
        "downstream_flows": [
            "flow-b",
            "flow-c"
        ]
    }'''

    # Execute Request
    dependencies_POST_response = client.send_request(
        url=URL,
        path="/api/impact-v2/flows/{flow_id}/dependencies/",
        method="POST",
        body=dependencies_POST_request_body,
        headers=headers,
        path_params={"flow_id": flow_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(dependencies_POST_response, "20x")


if __name__ == "__main__":
    test_dependencies_post()
