# Generated by Skyramp v1.3.14 on 2026-03-20 17:41:23.01654642 +0000 UTC m=+268.171154362
# Command: skyramp generate contract rest http://localhost:4200/api/checkpoints-v2/flow-runs/{flow_run_id}/checkpoints/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_test_create_checkpoint.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_run_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--request-data {"task_name":"process_data","state_data":{"progress":50}} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/checkpoints-v2/flow-runs/{flow_run_id}/checkpoints/ POST
def test_checkpoints_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_run_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    checkpoints_POST_request_body = r'''{
        "state_data": {
            "progress": 50
        },
        "task_name": "process_data"
    }'''

    # Execute Request
    checkpoints_POST_response = client.send_request(
        url=URL,
        path="/api/checkpoints-v2/flow-runs/{flow_run_id}/checkpoints/",
        method="POST",
        body=checkpoints_POST_request_body,
        headers=headers,
        path_params={"flow_run_id": flow_run_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(checkpoints_POST_response, "20x")


if __name__ == "__main__":
    test_checkpoints_post()
