# Generated by Skyramp v1.3.14 on 2026-03-20 17:38:53.620116178 +0000 UTC m=+166.656559947
# Command: skyramp generate contract rest http://localhost:4200/api/task-validation-v2/schemas/ \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_task_validation_schemas.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--query-params task_name=process_data,schema_type=pydantic \
# 		--request-data {"type":"object","properties":{"status":{"type":"string"},"result":{"type":"number"}}} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/task-validation-v2/schemas/ POST
def test_schemas_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    schemas_POST_request_body = r'''{
        "properties": {
            "result": {
                "type": "number"
            },
            "status": {
                "type": "string"
            }
        },
        "type": "object"
    }'''

    # Execute Request
    schemas_POST_response = client.send_request(
        url=URL,
        path="/api/task-validation-v2/schemas/",
        method="POST",
        body=schemas_POST_request_body,
        headers=headers,
        query_params={
            "schema_type": "pydantic",
            "task_name": "process_data"
        }
    )

    # Generated Assertions
    assert skyramp.check_status_code(schemas_POST_response, "20x")


if __name__ == "__main__":
    test_schemas_post()
