# Generated by Skyramp v1.3.14 on 2026-03-20 17:38:24.287542915 +0000 UTC m=+190.370473428
# Command: skyramp generate contract rest http://localhost:4200/api/quotas-v2/flows/{flow_id}/quota/ \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_quota_create_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--request-data {"max_concurrent_runs":10,"max_daily_runs":100,"max_hourly_runs":20} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/quotas-v2/flows/{flow_id}/quota/ POST
def test_quota_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    quota_POST_request_body = r'''{
        "max_concurrent_runs": 10,
        "max_daily_runs": 100,
        "max_hourly_runs": 20
    }'''

    # Execute Request
    quota_POST_response = client.send_request(
        url=URL,
        path="/api/quotas-v2/flows/{flow_id}/quota/",
        method="POST",
        body=quota_POST_request_body,
        headers=headers,
        path_params={"flow_id": flow_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(quota_POST_response, "20x")


if __name__ == "__main__":
    test_quota_post()
