# Generated by Skyramp v1.3.14 on 2026-03-22 20:29:56.291190125 +0000 UTC m=+180.131425257
# Command: skyramp generate contract rest http://localhost:4200/api/retry-budgets-v2/flows/{flow_id}/retry-budget/ \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_retry_budget_create.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--request-data {"max_retries_per_task":3,"max_retries_per_hour":50,"max_retries_per_day":200,"max_total_retry_duration_minutes":120,"enabled":true} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/retry-budgets-v2/flows/{flow_id}/retry-budget/ POST
def test_retry_budget_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    retry_budget_POST_request_body = r'''{
        "enabled": true,
        "max_retries_per_day": 200,
        "max_retries_per_hour": 50,
        "max_retries_per_task": 3,
        "max_total_retry_duration_minutes": 120
    }'''

    # Execute Request
    retry_budget_POST_response = client.send_request(
        url=URL,
        path="/api/retry-budgets-v2/flows/{flow_id}/retry-budget/",
        method="POST",
        body=retry_budget_POST_request_body,
        headers=headers,
        path_params={"flow_id": flow_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(retry_budget_POST_response, "20x")


if __name__ == "__main__":
    test_retry_budget_post()
