# Generated by Skyramp v1.3.13 on 2026-03-19 10:41:08.152810717 +0000 UTC m=+88.535668886
# Command: skyramp generate contract rest http://localhost:4200/api/validation-status/check \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_validation_status_check.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-data {"validated":true,"test_case":"SKYR-3650","scenario":"Multiple PRs on same branch"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/validation-status/check GET
def test_check_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_check_GET_response_body = r'''{
        "scenario": "Multiple PRs on same branch",
        "test_case": "SKYR-3650",
        "validated": true
    }'''

    # Execute Request
    check_GET_response = client.send_request(
        url=URL,
        path="/api/validation-status/check",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert check_GET_response.status_code == 200
    assert skyramp.check_schema(check_GET_response, expected_check_GET_response_body)
    assert skyramp.get_response_value(check_GET_response, "scenario") is not None
    assert skyramp.get_response_value(check_GET_response, "test_case") is not None
    assert skyramp.get_response_value(check_GET_response, "validated") is not None


if __name__ == "__main__":
    test_check_get()
