# Generated by Skyramp v1.3.14 on 2026-03-22 20:18:13.18383893 +0000 UTC m=+167.882042822
# Command: skyramp generate contract rest http://localhost:4200/api/task-validation-v2/flows/{flow_id}/validation-summary/ \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_flow_validation_summary.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/task-validation-v2/flows/{flow_id}/validation-summary/ GET
def test_validation_summary_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Expected Response Body
    expected_validation_summary_GET_response_body = r'''"string"'''

    # Execute Request
    validation_summary_GET_response = client.send_request(
        url=URL,
        path="/api/task-validation-v2/flows/{flow_id}/validation-summary/",
        method="GET",
        headers=headers,
        path_params={"flow_id": flow_id}
    )

    # Generated Assertions
    assert validation_summary_GET_response.status_code == 200
    assert skyramp.check_schema(validation_summary_GET_response, expected_validation_summary_GET_response_body)


if __name__ == "__main__":
    test_validation_summary_get()
