# Generated by Skyramp v1.3.14 on 2026-03-20 17:39:38.225840897 +0000 UTC m=+130.338327044
# Command: skyramp generate contract rest http://localhost:4200/api/impact-v2/flow-runs/{flow_run_id}/impact-analysis/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_flow_run_impact_analysis_get.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_run_id=7b3c4d5e-6f7a-8b9c-d0e1-f2a3b4c5d6e7 \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/impact-v2/flow-runs/{flow_run_id}/impact-analysis/ GET
def test_impact_analysis_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_run_id = "7b3c4d5e-6f7a-8b9c-d0e1-f2a3b4c5d6e7"

    # Execute Request
    impact_analysis_GET_response = client.send_request(
        url=URL,
        path="/api/impact-v2/flow-runs/{flow_run_id}/impact-analysis/",
        method="GET",
        headers=headers,
        path_params={"flow_run_id": flow_run_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(impact_analysis_GET_response, "20x")


if __name__ == "__main__":
    test_impact_analysis_get()
