# Generated by Skyramp v1.3.14 on 2026-03-20 18:12:17.237185985 +0000 UTC m=+216.423722999
# Command: skyramp generate contract rest http://localhost:4200/api/retry-budget-v2/flows/{flow_id}/retry-budget/ \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_retry_budget_post.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--query-params max_retries=10,reset_interval=daily \
# 		--request-data {"max_retries":10,"reset_interval":"daily"} \
# 		--response-data {"id":"budget-123","flow_id":"3fa85f64-5717-4562-b3fc-2c963f66afa6","max_retries":10,"reset_interval":"daily","current_usage":0} \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/retry-budget-v2/flows/{flow_id}/retry-budget/ POST
def test_retry_budget_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    retry_budget_POST_request_body = r'''{
        "max_retries": 10,
        "reset_interval": "daily"
    }'''

    # Expected Response Body
    expected_retry_budget_POST_response_body = r'''{
        "current_usage": 0,
        "flow_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "id": "budget-123",
        "max_retries": 10,
        "reset_interval": "daily"
    }'''

    # Execute Request
    retry_budget_POST_response = client.send_request(
        url=URL,
        path="/api/retry-budget-v2/flows/{flow_id}/retry-budget/",
        method="POST",
        body=retry_budget_POST_request_body,
        headers=headers,
        path_params={"flow_id": flow_id},
        query_params={
            "max_retries": "10",
            "reset_interval": "daily"
        }
    )

    # Generated Assertions
    assert retry_budget_POST_response.status_code == 200
    assert skyramp.check_schema(retry_budget_POST_response, expected_retry_budget_POST_response_body)
    assert skyramp.get_response_value(retry_budget_POST_response, "current_usage") is not None
    assert skyramp.get_response_value(retry_budget_POST_response, "flow_id") is not None
    assert skyramp.get_response_value(retry_budget_POST_response, "id") is not None


if __name__ == "__main__":
    test_retry_budget_post()
