# Generated by Skyramp v1.3.14 on 2026-03-20 17:56:06.27187453 +0000 UTC m=+236.087729836
# Command: skyramp generate contract rest http://localhost:4200/api/retry-budget-v2/flows/{flow_id}/retry-budget/ \
# 		--auth-header Authorization \
# 		--consumer \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_test_retry_budget_business_rule.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--request-data {"max_retries":5,"reset_interval":"daily"} \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp
from skyramp import MockV2


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/retry-budget-v2/flows/{flow_id}/retry-budget/ POST
def test_retry_budget_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    retry_budget_POST_request_body = r'''{
        "max_retries": 5,
        "reset_interval": "daily"
    }'''

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/retry-budget-v2/flows/{flow_id}/retry-budget/",
        method="POST",
        status_code=200,
        request_body=retry_budget_POST_request_body
    )
    client.apply_mock(mock)

    # Execute Request
    retry_budget_POST_response = client.send_request(
        url=URL,
        path="/api/retry-budget-v2/flows/{flow_id}/retry-budget/",
        method="POST",
        body=retry_budget_POST_request_body,
        headers=headers,
        path_params={"flow_id": flow_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(retry_budget_POST_response, "20x")

    client.remove_all_mocks()


if __name__ == "__main__":
    test_retry_budget_post()
