# Generated by Skyramp v1.3.14 on 2026-03-22 20:18:09.268796004 +0000 UTC m=+163.966999906
# Command: skyramp generate contract rest http://localhost:4200/api/task-validation-v2/task-runs/{task_run_id}/validation/ \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_task_validation_post.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params task_run_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--request-data {"check_name":"business_rule_validation","check_type":"business_rule","status":"passed","message":"All orders have valid customer references","details":{"rule":"customer_exists","violations":0}} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/task-validation-v2/task-runs/{task_run_id}/validation/ POST
def test_validation_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    task_run_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    validation_POST_request_body = r'''{
        "check_name": "business_rule_validation",
        "check_type": "business_rule",
        "details": {
            "rule": "customer_exists",
            "violations": 0
        },
        "message": "All orders have valid customer references",
        "status": "passed"
    }'''

    # Expected Response Body
    expected_validation_POST_response_body = r'''"string"'''

    # Execute Request
    validation_POST_response = client.send_request(
        url=URL,
        path="/api/task-validation-v2/task-runs/{task_run_id}/validation/",
        method="POST",
        body=validation_POST_request_body,
        headers=headers,
        path_params={"task_run_id": task_run_id}
    )

    # Generated Assertions
    assert validation_POST_response.status_code == 200
    assert skyramp.check_schema(validation_POST_response, expected_validation_POST_response_body)


if __name__ == "__main__":
    test_validation_post()
