# Generated by Skyramp v1.3.14 on 2026-03-20 17:38:50.632943759 +0000 UTC m=+163.669387519
# Command: skyramp generate contract rest http://localhost:4200/api/task-validation-v2/validate/ \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_task_validation_validate.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--query-params task_name=process_data \
# 		--request-data {"status":"success","result":42} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/task-validation-v2/validate/ POST
def test_validate_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    validate_POST_request_body = r'''{
        "result": 42,
        "status": "success"
    }'''

    # Execute Request
    validate_POST_response = client.send_request(
        url=URL,
        path="/api/task-validation-v2/validate/",
        method="POST",
        body=validate_POST_request_body,
        headers=headers,
        query_params={"task_name": "process_data"}
    )

    # Generated Assertions
    assert skyramp.check_status_code(validate_POST_response, "20x")


if __name__ == "__main__":
    test_validate_post()
