# Generated by Skyramp v1.3.13 on 2026-03-19 10:41:07.678992079 +0000 UTC m=+88.061850257
# Command: skyramp generate contract rest http://localhost:4200/api/validation-status/health \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_validation_status_health.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-data {"status":"healthy","validation":"SKYR-3650","description":"Self-trigger detection validation endpoint"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/validation-status/health GET
def test_health_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_health_GET_response_body = r'''{
        "description": "Self-trigger detection validation endpoint",
        "status": "healthy",
        "validation": "SKYR-3650"
    }'''

    # Execute Request
    health_GET_response = client.send_request(
        url=URL,
        path="/api/validation-status/health",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert health_GET_response.status_code == 200
    assert skyramp.check_schema(health_GET_response, expected_health_GET_response_body)
    assert skyramp.get_response_value(health_GET_response, "description") is not None
    assert skyramp.get_response_value(health_GET_response, "status") is not None
    assert skyramp.get_response_value(health_GET_response, "validation") is not None


if __name__ == "__main__":
    test_health_get()
