# Generated by Skyramp v1.3.14 on 2026-03-20 18:39:34.639076755 +0000 UTC m=+92.990863823
# Command: skyramp generate contract rest http://localhost:4200/api/flow-impact/runs/{run_id}/downstream \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params run_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-impact/runs/{run_id}/downstream GET
def test_downstream_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    run_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Expected Response Body
    expected_downstream_GET_response_body = r'''{"run_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6", "downstream_flows": [{"flow_id": "flow-2", "dependency_type": "direct"}], "total_affected": 2}'''

    # Execute Request
    downstream_GET_response = client.send_request(
        url=URL,
        path="/api/flow-impact/runs/{run_id}/downstream",
        method="GET",
        headers=headers,
        path_params={"run_id": run_id}
    )

    # Generated Assertions
    assert downstream_GET_response.status_code == 200
    assert skyramp.check_schema(downstream_GET_response, expected_downstream_GET_response_body)


if __name__ == "__main__":
    test_downstream_get()
