# Generated by Skyramp v1.3.14 on 2026-03-20 17:32:10.486480984 +0000 UTC m=+228.202422556
# Command: skyramp generate contract rest http://localhost:4200/api/flow-impact/runs/{run_id}/downstream \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params run_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--response-data {"run_id":"3fa85f64-5717-4562-b3fc-2c963f66afa6","downstream_flows":[{"flow_id":"flow-2","dependency_type":"direct"},{"flow_id":"flow-3","dependency_type":"indirect"}],"total_affected":2} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-impact/runs/{run_id}/downstream GET
def test_downstream_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    run_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Expected Response Body
    expected_downstream_GET_response_body = r'''{
        "downstream_flows": [
            {
                "dependency_type": "direct",
                "flow_id": "flow-2"
            },
            {
                "dependency_type": "indirect",
                "flow_id": "flow-3"
            }
        ],
        "run_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "total_affected": 2
    }'''

    # Execute Request
    downstream_GET_response = client.send_request(
        url=URL,
        path="/api/flow-impact/runs/{run_id}/downstream",
        method="GET",
        headers=headers,
        path_params={"run_id": run_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(downstream_GET_response, "20x")
    assert skyramp.check_schema(downstream_GET_response, expected_downstream_GET_response_body)
    assert skyramp.get_response_value(downstream_GET_response, "downstream_flows.0.dependency_type") is not None
    assert skyramp.get_response_value(downstream_GET_response, "downstream_flows.0.flow_id") is not None
    assert skyramp.get_response_value(downstream_GET_response, "downstream_flows.1.dependency_type") is not None


if __name__ == "__main__":
    test_downstream_get()
