# Generated by Skyramp v1.3.14 on 2026-03-20 17:28:54.81978307 +0000 UTC m=+86.928398384
# Command: skyramp generate contract rest http://localhost:4200/flow-traces/export/{run_id} \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params run_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--query-params format=json \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /flow-traces/export/{run_id} GET
def test_export_run_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    run_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Execute Request
    export_run_id_GET_response = client.send_request(
        url=URL,
        path="/flow-traces/export/{run_id}",
        method="GET",
        headers=headers,
        path_params={"run_id": run_id},
        query_params={"format": "json"}
    )

    # Generated Assertions
    assert skyramp.check_status_code(export_run_id_GET_response, "20x")


if __name__ == "__main__":
    test_export_run_id_get()
