# Generated by Skyramp v1.3.14 on 2026-03-20 17:52:15.398482028 +0000 UTC m=+157.681001370
# Command: skyramp generate contract rest http://localhost:4200/api/flow-costs-v2/run-costs/flow-run/{flow_run_id} \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_run_id=1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-costs-v2/run-costs/flow-run/{flow_run_id} GET
def test_flow_run_flow_run_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_run_id = "1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d"

    # Execute Request
    flow_run_flow_run_id_GET_response = client.send_request(
        url=URL,
        path="/api/flow-costs-v2/run-costs/flow-run/{flow_run_id}",
        method="GET",
        headers=headers,
        path_params={"flow_run_id": flow_run_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(flow_run_flow_run_id_GET_response, "20x")


if __name__ == "__main__":
    test_flow_run_flow_run_id_get()
