# Generated by Skyramp v1.3.14 on 2026-03-20 17:52:17.863798277 +0000 UTC m=+237.201861748
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output flow_dep_security_boundary_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-dep-security-boundary.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Execute Request
    graph_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-dependencies/flows/3fa85f64-5717-4562-b3fc-2c963f66afa6/graph",
        method="GET"
    )
    # Generated Assertions
    assert graph_GET_response.status_code == 401


if __name__ == "__main__":
    test_integration()
