# Generated by Skyramp v1.3.14 on 2026-03-20 18:03:51.467286507 +0000 UTC m=+95.675568476
# Command: skyramp generate contract rest http://localhost:4200/flow-costs-v2/profiles/flow/{flow_id} \
# 		--framework pytest \
# 		--language python \
# 		--method DELETE \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /flow-costs-v2/profiles/flow/{flow_id} DELETE
def test_flow_flow_id_delete():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Execute Request
    flow_flow_id_DELETE_response = client.send_request(
        url=URL,
        path="/flow-costs-v2/profiles/flow/{flow_id}",
        method="DELETE",
        headers=headers,
        path_params={"flow_id": flow_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(flow_flow_id_DELETE_response, "20x")


if __name__ == "__main__":
    test_flow_flow_id_delete()
