# Generated by Skyramp v1.3.14 on 2026-03-20 17:23:37.554816876 +0000 UTC m=+113.882343359
# Command: skyramp generate contract rest http://localhost:4200/api/metrics/flows \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/metrics/flows GET
def test_flows_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    flows_GET_response = client.send_request(
        url=URL,
        path="/api/metrics/flows",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(flows_GET_response, "20x")


if __name__ == "__main__":
    test_flows_get()
