# Generated by Skyramp v1.3.14 on 2026-03-20 17:54:01.200594913 +0000 UTC m=+290.400824789
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output flow_impact_blast_radius_notify_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-impact-blast-radius-notify.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    runs = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Execute Request
    blast_radius_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-impact/runs/{runs}/blast-radius",
        method="GET",
        headers=headers,
        path_params={"runs": runs}
    )
    # Generated Assertions
    assert blast_radius_GET_response.status_code == 200

    # Request Body
    notify_POST_request_body = r'''{}'''
    
    # Execute Request
    notify_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-impact/runs/{runs}/notify",
        method="POST",
        body=notify_POST_request_body,
        headers=headers,
        path_params={"runs": skyramp.get_response_value(blast_radius_GET_response, "run_id")},
        query_params={"impact_level": ["high"]}
    )
    # Generated Assertions
    assert notify_POST_response.status_code == 200


if __name__ == "__main__":
    test_integration()
