# Generated by Skyramp v1.3.14 on 2026-03-22 21:14:24.058851795 +0000 UTC m=+235.031387975
# Command: skyramp generate contract rest http://127.0.0.1:4200/api/checkpoints-v2/flow-runs/{flow_run_id}/checkpoints/ \
# 		--api-schema http://127.0.0.1:4200/api/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output flow_run_checkpoints_GET_provider_contract_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_run_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--response-data {"flow_run_id":"3fa85f64-5717-4562-b3fc-2c963f66afa6","checkpoints":[{"id":"checkpoint-1","name":"data_extracted","state":"completed","created_at":"2026-03-20T10:00:00","metadata":{"task_count":1,"data_size_mb":125}}],"total_checkpoints":4,"latest_checkpoint_id":"checkpoint-4"} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

# contract test for /api/checkpoints-v2/flow-runs/{flow_run_id}/checkpoints/ GET
def test_checkpoints_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_run_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Expected Response Body
    expected_checkpoints_GET_response_body = r'''{
        "checkpoints": [
            {
                "created_at": "2026-03-20T10:00:00",
                "id": "checkpoint-1",
                "metadata": {
                    "data_size_mb": 125,
                    "task_count": 1
                },
                "name": "data_extracted",
                "state": "completed"
            }
        ],
        "flow_run_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "latest_checkpoint_id": "checkpoint-4",
        "total_checkpoints": 4
    }'''

    # Execute Request
    checkpoints_GET_response = client.send_request(
        url=URL,
        path="/api/checkpoints-v2/flow-runs/{flow_run_id}/checkpoints/",
        method="GET",
        headers=headers,
        path_params={"flow_run_id": flow_run_id}
    )

    # Generated Assertions
    assert checkpoints_GET_response.status_code == 200
    assert skyramp.check_schema(checkpoints_GET_response, expected_checkpoints_GET_response_body)
    assert skyramp.get_response_value(checkpoints_GET_response, "checkpoints.0.created_at") is not None
    assert skyramp.get_response_value(checkpoints_GET_response, "checkpoints.0.id") is not None
    assert skyramp.get_response_value(checkpoints_GET_response, "checkpoints.0.metadata.data_size_mb") is not None


if __name__ == "__main__":
    test_checkpoints_get()
