# Generated by Skyramp v1.3.14 on 2026-03-20 17:53:46.151992766 +0000 UTC m=+275.352222652
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output flow_impact_auth_boundary_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-impact-auth-boundary.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Execute Request
    downstream_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-impact/runs/3fa85f64-5717-4562-b3fc-2c963f66afa6/downstream",
        method="GET"
    )
    # Generated Assertions
    assert downstream_GET_response.status_code == 401


if __name__ == "__main__":
    test_integration()
