# Generated by Skyramp v1.3.14 on 2026-03-20 17:52:17.954021832 +0000 UTC m=+160.236541164
# Command: skyramp generate contract rest http://localhost:4200/api/flow-costs-v2/history/flow/{flow_id} \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_id=7f8a9b2c-3d4e-5f6a-7b8c-9d0e1f2a3b4c \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-costs-v2/history/flow/{flow_id} GET
def test_flow_flow_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_id = "7f8a9b2c-3d4e-5f6a-7b8c-9d0e1f2a3b4c"

    # Execute Request
    flow_flow_id_GET_response = client.send_request(
        url=URL,
        path="/api/flow-costs-v2/history/flow/{flow_id}",
        method="GET",
        headers=headers,
        path_params={"flow_id": flow_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(flow_flow_id_GET_response, "20x")


if __name__ == "__main__":
    test_flow_flow_id_get()
