# Generated by Skyramp v1.3.14 on 2026-03-20 17:52:21.359340403 +0000 UTC m=+240.697403874
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output flow_dep_validate_business_rule_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-dep-validate-business-rule.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flows = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    validate_POST_request_body = r'''{}'''
    
    # Execute Request
    validate_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-dependencies/flows/{flows}/validate",
        method="POST",
        body=validate_POST_request_body,
        headers=headers,
        path_params={"flows": flows}
    )
    # Generated Assertions
    assert validate_POST_response.status_code == 200


if __name__ == "__main__":
    test_integration()
