# Generated by Skyramp v1.3.14 on 2026-03-20 17:38:58.387233333 +0000 UTC m=+121.418999637
# Command: skyramp generate fuzz rest http://localhost:4200/api/retry-budget-v2/flows/{flow_id}/retry-budget/ \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--request-data {"max_retries":5,"reset_interval":"daily"} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# fuzz test for /api/retry-budget-v2/flows/{flow_id}/retry-budget/ POST
def test_retry_budget_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    retry_budget_POST_request_body = r'''{
      "max_retries": 5,
      "reset_interval": "daily"
    }'''
    
    # Fuzz strategies
    retry_budget_post_fuzzed_body = {
        "max_retries": -10,
        "reset_interval": "0123456789"
    }
    # Fuzz status codes
    expected_retry_budget_post_status_code = {
        "max_retries": "40x",
        "reset_interval": "40x"
    }
    # Fuzz status codes for Null values
    expected_retry_budget_post_null_status_code = {
        "max_retries": "40x",
        "reset_interval": "40x"
    }

    # Execute Request
    retry_budget_POST_response = client.send_request(
        url=URL,
        path="/api/retry-budget-v2/flows/{flow_id}/retry-budget/",
        method="POST",
        body=retry_budget_POST_request_body,
        headers=headers,
        path_params={"flow_id": flow_id},
        expected_code="20x"
    )

    for key in skyramp.iterate(retry_budget_post_fuzzed_body):
        # Execute Request
        retry_budget_POST_response = client.send_request(
            url=URL,
            path="/api/retry-budget-v2/flows/{flow_id}/retry-budget/",
            method="POST",
            body=retry_budget_POST_request_body,
            headers=headers,
            path_params={"flow_id": flow_id},
            data_override={key: skyramp.get_value(retry_budget_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_retry_budget_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(retry_budget_post_fuzzed_body, key) }'
        )

        # Execute Request
        retry_budget_POST_response = client.send_request(
            url=URL,
            path="/api/retry-budget-v2/flows/{flow_id}/retry-budget/",
            method="POST",
            body=retry_budget_POST_request_body,
            headers=headers,
            path_params={"flow_id": flow_id},
            data_override={key: None},
            expected_code=skyramp.get_value(expected_retry_budget_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_retry_budget_post()
