# Generated by Skyramp v1.3.14 on 2026-03-22 21:10:31.983924279 +0000 UTC m=+129.353247699
# Command: skyramp generate fuzz rest http://localhost:4200/traces-v2/flow-runs/{flow_run_id}/traces/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_run_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# fuzz test for /traces-v2/flow-runs/{flow_run_id}/traces/ GET
def test_traces_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_run_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Execute Request
    traces_GET_response = client.send_request(
        url=URL,
        path="/traces-v2/flow-runs/{flow_run_id}/traces/",
        method="GET",
        headers=headers,
        path_params={"flow_run_id": flow_run_id},
        expected_code="20x"
    )

    assert client.is_success()


if __name__ == "__main__":
    test_traces_get()
