# Generated by Skyramp v1.3.14 on 2026-03-20 18:38:18.12050231 +0000 UTC m=+163.796479049
# Command: skyramp generate contract rest http://localhost:4200/api/flow-dependencies/flows/{flow_id}/graph \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--response-data {"flow_id":"3fa85f64-5717-4562-b3fc-2c963f66afa6","nodes":["task-1","task-2","task-3"],"edges":[{"from":"task-1","to":"task-2"},{"from":"task-2","to":"task-3"}]} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-dependencies/flows/{flow_id}/graph GET
def test_graph_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Expected Response Body
    expected_graph_GET_response_body = r'''{
        "edges": [
            {
                "from": "task-1",
                "to": "task-2"
            },
            {
                "from": "task-2",
                "to": "task-3"
            }
        ],
        "flow_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "nodes": [
            "task-1",
            "task-2",
            "task-3"
        ]
    }'''

    # Execute Request
    graph_GET_response = client.send_request(
        url=URL,
        path="/api/flow-dependencies/flows/{flow_id}/graph",
        method="GET",
        headers=headers,
        path_params={"flow_id": flow_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(graph_GET_response, "20x")
    assert skyramp.check_schema(graph_GET_response, expected_graph_GET_response_body)
    assert skyramp.get_response_value(graph_GET_response, "edges.0.from") is not None
    assert skyramp.get_response_value(graph_GET_response, "edges.0.to") is not None
    assert skyramp.get_response_value(graph_GET_response, "edges.1.from") is not None


if __name__ == "__main__":
    test_graph_get()
