# Generated by Skyramp v1.3.14 on 2026-03-20 18:09:51.687035556 +0000 UTC m=+190.217113857
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output integration_test_trace_workflow.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_trace_workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    flow_runs = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/api/traces-v2/flow-runs/{flow-runs}/trace/",
        method="GET",
        path_params={"flow-runs": flow_runs}
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/api/traces-v2/flow-runs/{flow-runs}/trace/{trace}/spans/",
        method="GET",
        path_params={
            "flow-runs": skyramp.get_response_value(endpoint_1_GET_response, "flow_run_id"),
            "trace": skyramp.get_response_value(endpoint_1_GET_response, "trace_id")
        }
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
