# Generated by Skyramp v1.3.14 on 2026-03-20 17:24:10.791967307 +0000 UTC m=+147.119493799
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output integration_test_post_custom_metric.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_post_custom_metric.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    api = "api"

    # Request Body
    custom_POST_request_body = r'''{
        "name": "request_latency_ms",
        "tags": {
            "env": "prod",
            "service": "api"
        },
        "value": 42.5
    }'''
    
    # Execute Request
    custom_POST_response = client.send_request(
        url=URL_localhost,
        path="/{api}/metrics/custom",
        method="POST",
        body=custom_POST_request_body,
        path_params={"api": api},
        data_override={"tags.service": api}
    )
    # Generated Assertions
    assert custom_POST_response.status_code == 200


if __name__ == "__main__":
    test_integration()
