# Generated by Skyramp v1.3.14 on 2026-03-20 17:52:47.497877868 +0000 UTC m=+237.888824616
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output integration_budget_set_check_run_usage_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_budget_set_check_run_usage.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    runs = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    budgets_POST_request_body = r'''{
        "flow_id": "flow-workflow-run-test",
        "max_retries": 10
    }'''
    
    # Execute Request
    budgets_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/task-retries/budgets",
        method="POST",
        body=budgets_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert budgets_POST_response.status_code == 200

    # Execute Request
    usage_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/task-retries/runs/{runs}/usage",
        method="GET",
        headers=headers,
        path_params={"runs": runs}
    )
    # Generated Assertions
    assert usage_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
