# Generated by Skyramp v1.3.14 on 2026-03-20 18:38:56.947443982 +0000 UTC m=+202.623420721
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output integration_test_flow_dependency_full_workflow.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-dependency-full-workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flows = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Execute Request
    graph_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-dependencies/flows/{flows}/graph",
        method="GET",
        headers=headers,
        path_params={"flows": flows}
    )
    # Generated Assertions
    assert graph_GET_response.status_code == 200

    # Request Body
    validate_POST_request_body = r'''{}'''
    
    # Execute Request
    validate_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-dependencies/flows/{flows}/validate-graph",
        method="POST",
        body=validate_POST_request_body,
        headers=headers,
        path_params={"flows": skyramp.get_response_value(graph_GET_response, "flow_id")}
    )
    # Generated Assertions
    assert validate_POST_response.status_code == 200

    # Execute Request
    analysis_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-dependencies/flows/{flows}/analysis",
        method="GET",
        headers=headers,
        path_params={"flows": skyramp.get_response_value(graph_GET_response, "flow_id")}
    )
    # Generated Assertions
    assert analysis_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
