# Generated by Skyramp v1.3.14 on 2026-03-20 19:01:38.857184979 +0000 UTC m=+189.336255983
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output integration_test_checkpoint_workflow.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_checkpoint-workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_runs = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "progress": 50
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/checkpoints-v2/flow-runs/{flow-runs}/checkpoints/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers,
        path_params={"flow-runs": flow_runs},
        query_params={"task_name": ["process_data"]}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/checkpoints-v2/flow-runs/{flow-runs}/checkpoints/",
        method="GET",
        headers=headers,
        path_params={"flow-runs": skyramp.get_response_value(endpoint_1_POST_response, "flow_run_id")}
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200

    # Request Body
    endpoint_2_POST_request_body = r'''{}'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/checkpoints-v2/flow-runs/{flow-runs}/restore/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers,
        path_params={"flow-runs": skyramp.get_response_value(endpoint_1_POST_response, "flow_run_id")},
        query_params={"checkpoint_id": ["checkpoint-new"]}
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201


if __name__ == "__main__":
    test_integration()
