# Generated by Skyramp v1.3.14 on 2026-03-22 21:22:05.3473841 +0000 UTC m=+348.658072907
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output integration_test_checkpoint_validation_rejected.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_checkpoint-validation-rejected.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    runs_3fa85f64_5717_4562_b3fc_2c963f66afa6_POST_request_body = r'''{
        "step": 1,
        "workflow_state": "running"
    }'''
    
    # Execute Request
    runs_3fa85f64_5717_4562_b3fc_2c963f66afa6_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-checkpoints/runs/3fa85f64-5717-4562-b3fc-2c963f66afa6",
        method="POST",
        body=runs_3fa85f64_5717_4562_b3fc_2c963f66afa6_POST_request_body,
        query_params={
            "task_name": ["workflow-task"],
            "validation_status": ["pending"]
        }
    )
    # Generated Assertions
    assert runs_3fa85f64_5717_4562_b3fc_2c963f66afa6_POST_response.status_code == 400


if __name__ == "__main__":
    test_integration()
