# Generated by Skyramp v1.3.14 on 2026-03-20 18:06:55.166946873 +0000 UTC m=+207.848366691
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output integration_test_quota_business_rule.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_quota-business-rule-limits.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flows = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "max_concurrent_runs": 5,
        "max_daily_runs": 50,
        "max_hourly_runs": 10
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/quotas-v2/flows/{flows}/quota/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers,
        path_params={"flows": flows}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 200

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/quotas-v2/flows/{flows}/quota/",
        method="GET",
        headers=headers,
        path_params={"flows": skyramp.get_response_value(endpoint_1_POST_response, "flow_id")}
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200

    # Request Body
    endpoint_1_PATCH_request_body = r'''{
        "max_concurrent_runs": 15,
        "max_daily_runs": 50
    }'''
    
    # Execute Request
    endpoint_1_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/quotas-v2/flows/{flows}/quota/",
        method="PATCH",
        body=endpoint_1_PATCH_request_body,
        headers=headers,
        path_params={"flows": skyramp.get_response_value(endpoint_1_POST_response, "flow_id")},
        data_override={"max_daily_runs": skyramp.get_response_value(endpoint_1_GET_response, "max_daily_runs")}
    )
    # Generated Assertions
    assert endpoint_1_PATCH_response.status_code == 200

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/quotas-v2/flows/{flows}/quota/usage/",
        method="GET",
        headers=headers,
        path_params={"flows": skyramp.get_response_value(endpoint_1_POST_response, "flow_id")}
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
