# Generated by Skyramp v1.3.14 on 2026-03-22 21:13:59.243703331 +0000 UTC m=+210.216239491
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output integration_test_checkpoints_v2_create_list_workflow.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_checkpoints-v2-create-list-workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_ = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    flow_runs = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    endpoint_1_POST_request_body = r'''{}'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_,
        path="/api/checkpoints-v2/flow-runs/{flow-runs}/checkpoints/",
        method="POST",
        body=endpoint_1_POST_request_body,
        path_params={"flow-runs": flow_runs}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 200

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_,
        path="/api/checkpoints-v2/flow-runs/{flow-runs}/checkpoints/",
        method="GET",
        path_params={"flow-runs": skyramp.get_response_value(endpoint_1_POST_response, "flow_run_id")}
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
