# Generated by Skyramp v1.3.14 on 2026-03-20 19:02:32.038429828 +0000 UTC m=+147.203874423
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output integration_test_set_retry_budget_business_rule.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_set_retry_budget_business_rule.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flows = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "max_retries": 5,
        "reset_interval": "daily"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/retry-budget-v2/flows/{flows}/retry-budget/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers,
        path_params={"flows": flows}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 200


if __name__ == "__main__":
    test_integration()
