# Generated by Skyramp v1.3.14 on 2026-03-20 17:52:20.963267335 +0000 UTC m=+211.354214103
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output integration_unauthenticated_task_retries_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_unauthenticated_task_retries.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    budgets_POST_request_body = r'''{
        "flow_id": "flow-unauth-test",
        "max_retries": 5
    }'''
    
    # Execute Request
    budgets_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/task-retries/budgets",
        method="POST",
        body=budgets_POST_request_body
    )
    # Generated Assertions
    assert budgets_POST_response.status_code == 401


if __name__ == "__main__":
    test_integration()
