# Generated by Skyramp v1.3.14 on 2026-03-20 18:59:12.035010134 +0000 UTC m=+208.505824900
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output integration_flow_cost_tracking_workflow.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow_cost_tracking_workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    flow_id = "4ab96e75-6828-5673-c4fd-3d074g77bgb7"
    flow_run_id = "5bc07f86-7939-6784-d5ge-4e185h88chc8"

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "cost_per_second": 0.01,
        "cost_per_task": 0.05,
        "currency": "USD",
        "flow_id": "4ab96e75-6828-5673-c4fd-3d074g77bgb7"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs-v2/profiles/",
        method="POST",
        body=endpoint_1_POST_request_body,
        data_override={"flow_id": flow_id}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 200

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "cost_breakdown": {
            "compute": 10,
            "storage": 2.5
        },
        "execution_seconds": 1245,
        "flow_run_id": "5bc07f86-7939-6784-d5ge-4e185h88chc8",
        "task_count": 10,
        "total_cost": 12.5
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs-v2/run-costs/",
        method="POST",
        body=endpoint_2_POST_request_body,
        data_override={"flow_run_id": flow_run_id}
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 200

    # Execute Request
    flow_run_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs-v2/run-costs/flow-run/{flow-run}",
        method="GET",
        path_params={"flow-run": flow_run_id}
    )
    # Generated Assertions
    assert flow_run_GET_response.status_code == 200

    # Execute Request
    flow_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs-v2/history/flow/{flow}",
        method="GET",
        path_params={"flow": flow_id}
    )
    # Generated Assertions
    assert flow_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
