# Generated by Skyramp v1.3.14 on 2026-03-20 17:47:44.513750072 +0000 UTC m=+215.119590320
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--chaining-key id \
# 		--framework pytest \
# 		--language python \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow_cost_tracking_workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    profiles_POST_request_body = r'''{
        "cost_per_second": 0.05,
        "flow_id": "flow-test-123"
    }'''
    
    # Execute Request
    profiles_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/profiles",
        method="POST",
        body=profiles_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert profiles_POST_response.status_code == 200

    # Execute Request
    profiles_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/profiles",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert profiles_GET_response.status_code == 200

    # Execute Request
    runs_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/runs/{runs}",
        method="GET",
        headers=headers,
        path_params={"runs": skyramp.get_response_value(profiles_POST_response, "id")}
    )
    # Generated Assertions
    assert runs_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
