# Generated by Skyramp v1.3.14 on 2026-03-20 19:01:18.746767072 +0000 UTC m=+181.738815491
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output integration_traces_v2_full_workflow_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_traces-v2-full-workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    flow_runs = "9c2d4e6f-8a1b-3c5d-7e9f-0a2b4c6d8e0f"

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/traces-v2/flow-runs/{flow-runs}/trace/",
        method="GET",
        path_params={"flow-runs": flow_runs}
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/traces-v2/flow-runs/{flow-runs}/trace/{trace}/spans/",
        method="GET",
        path_params={
            "flow-runs": skyramp.get_response_value(endpoint_1_GET_response, "flow_run_id"),
            "trace": skyramp.get_response_value(endpoint_1_GET_response, "trace_id")
        }
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
