# Generated by Skyramp v1.3.14 on 2026-03-20 17:56:42.31902306 +0000 UTC m=+272.134878370
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output integration_test_retry_budget_workflow.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_retry-budget-workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_runs = "7c9b3e12-4f85-4a1d-9c78-2b5e6d0a1f34"
    flows = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "max_retries": 5,
        "reset_interval": "weekly"
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/retry-budget-v2/flows/{flows}/retry-budget/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers,
        path_params={"flows": flows}
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 200

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/retry-budget-v2/flow-runs/{flow-runs}/retry-usage/",
        method="GET",
        headers=headers,
        path_params={"flow-runs": flow_runs}
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
