# Generated by Skyramp v1.3.14 on 2026-03-22 21:16:14.489870018 +0000 UTC m=+225.247714018
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output integration_test_task_validation_workflow.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_task-validation-workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    task_runs = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/task-validation-v2/task-runs/{task-runs}/validation/",
        method="GET",
        headers=headers,
        path_params={"task-runs": task_runs}
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "check_name": "schema_validation",
        "check_type": "schema",
        "message": "Output matches expected schema",
        "status": "passed"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/task-validation-v2/task-runs/{task-runs}/validation/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers,
        path_params={"task-runs": skyramp.get_response_value(endpoint_1_GET_response, "task_run_id")}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 200


if __name__ == "__main__":
    test_integration()
