# Generated by Skyramp v1.3.14 on 2026-03-22 20:22:38.914327688 +0000 UTC m=+196.021045107
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output integration_test_cost_profile_crud.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_cost_profile_crud_lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    flows = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "cost_per_gb_memory": 0.0025,
        "cost_per_second": 0.0001,
        "cost_per_task": 0.05,
        "currency": "USD",
        "fixed_cost_per_run": 0.1
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs-v2/flows/{flows}/cost-profile/",
        method="POST",
        body=endpoint_1_POST_request_body,
        path_params={"flows": flows}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 200

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs-v2/flows/{flows}/cost-profile/",
        method="GET",
        path_params={"flows": skyramp.get_response_value(endpoint_1_POST_response, "flow_id")}
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200

    # Execute Request
    endpoint_1_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs-v2/flows/{flows}/cost-profile/",
        method="DELETE",
        path_params={"flows": skyramp.get_response_value(endpoint_1_POST_response, "flow_id")}
    )
    # Generated Assertions
    assert endpoint_1_DELETE_response.status_code == 200


if __name__ == "__main__":
    test_integration()
