# Generated by Skyramp v1.3.14 on 2026-03-20 18:33:31.261598201 +0000 UTC m=+181.507021746
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output integration_test_schema_persistence.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_task-validation-schema-persistence.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    schemas_POST_request_body = r'''{
        "properties": {
            "output": {
                "type": "number"
            }
        },
        "type": "object"
    }'''
    
    # Execute Request
    schemas_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/task-validation/schemas",
        method="POST",
        body=schemas_POST_request_body,
        query_params={"task_name": ["transform_data_task"]}
    )
    # Generated Assertions
    assert schemas_POST_response.status_code == 201

    # Execute Request
    schemas_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/task-validation/schemas",
        method="GET"
    )
    # Generated Assertions
    assert schemas_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
