# Generated by Skyramp v1.3.14 on 2026-03-20 18:33:29.678347589 +0000 UTC m=+179.923771134
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output integration_test_schema_validate_workflow.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_task-validation-schema-validate-workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    schemas_POST_request_body = r'''{
        "properties": {
            "result": {
                "type": "string"
            }
        },
        "type": "object"
    }'''
    
    # Execute Request
    schemas_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/task-validation/schemas",
        method="POST",
        body=schemas_POST_request_body,
        query_params={"task_name": ["process_data_task"]}
    )
    # Generated Assertions
    assert schemas_POST_response.status_code == 201

    # Request Body
    validate_POST_request_body = r'''{
        "result": "processed_successfully"
    }'''
    
    # Execute Request
    validate_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/task-validation/validate",
        method="POST",
        body=validate_POST_request_body,
        query_params={"task_id": ["task-abc-123"]}
    )
    # Generated Assertions
    assert validate_POST_response.status_code == 201


if __name__ == "__main__":
    test_integration()
