# Generated by Skyramp v1.3.14 on 2026-03-20 17:40:05.825532929 +0000 UTC m=+157.938019116
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output integration_register_and_graph_workflow.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_register_and_graph_workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    flows = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "downstream_flows": [
            "flow-c",
            "flow-d",
            "flow-e"
        ]
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/api/impact-v2/flows/{flows}/dependencies/",
        method="POST",
        body=endpoint_1_POST_request_body,
        path_params={"flows": flows}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 200

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/api/impact-v2/flows/{flows}/dependency-graph/",
        method="GET",
        path_params={"flows": skyramp.get_response_value(endpoint_1_POST_response, "flow_id")}
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
