# Generated by Skyramp v1.3.14 on 2026-03-22 20:10:30.857431654 +0000 UTC m=+199.125272424
# Command: skyramp generate integration rest \
# 		--chaining-key id \
# 		--framework pytest \
# 		--language python \
# 		--output integration_traces_workflow_spans_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_traces_workflow_create_flow_run_verify_spans.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_2_POST_request_body = r'''{
        "name": "skyramp-test-traces-workflow-flow"
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/api/flows/",
        method="POST",
        body=endpoint_2_POST_request_body
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "flow_id": "4ab96e75-6828-5673-c4gd-3d074g77bfb7",
        "name": "skyramp-test-traces-workflow-run"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/api/flow-runs/",
        method="POST",
        body=endpoint_1_POST_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    endpoint_3_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/api/traces-v2/flow-runs/{flow-runs}/traces/",
        method="GET",
        path_params={"flow-runs": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_3_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
