# Generated by Skyramp v1.3.14 on 2026-03-20 18:36:38.850156527 +0000 UTC m=+208.092226967
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output integration_add_span_verify_trace_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_add-span-verify-trace.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    runs = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    spans_POST_request_body = r'''{}'''
    
    # Execute Request
    spans_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-traces/runs/{runs}/spans",
        method="POST",
        body=spans_POST_request_body,
        path_params={"runs": runs},
        query_params={
            "duration_ms": ["300"],
            "span_name": ["data-validation-task"]
        }
    )
    # Generated Assertions
    assert spans_POST_response.status_code == 200

    # Execute Request
    runs_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-traces/runs/{runs}",
        method="GET",
        path_params={"runs": skyramp.get_response_value(spans_POST_response, "run_id")}
    )
    # Generated Assertions
    assert runs_GET_response.status_code == 200
    assert skyramp.get_response_value(runs_GET_response, "trace_version") is not None


if __name__ == "__main__":
    test_integration()
