# Generated by Skyramp v1.3.14 on 2026-03-20 17:30:29.073841156 +0000 UTC m=+218.081760598
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output integration_test_quota_full_lifecycle.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-quota-full-lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_id = "flow-lifecycle-1"

    # Execute Request
    limits_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-quotas/limits",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert limits_GET_response.status_code == 200

    # Request Body
    limits_POST_request_body = r'''{}'''
    
    # Execute Request
    limits_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-quotas/limits",
        method="POST",
        body=limits_POST_request_body,
        headers=headers,
        query_params={
            "flow_id": flow_id,
            "max_concurrent_runs": ["8"],
            "max_daily_runs": ["80"]
        }
    )
    # Generated Assertions
    assert limits_POST_response.status_code == 201

    # Execute Request
    usage_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-quotas/usage/{usage}",
        method="GET",
        headers=headers,
        path_params={"usage": skyramp.get_response_value(limits_POST_response, "flow_id")}
    )
    # Generated Assertions
    assert usage_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
