# Generated by Skyramp v1.3.14 on 2026-03-20 17:38:45.7855616 +0000 UTC m=+211.868492086
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output integration_quota_lifecycle_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_quota_lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flows = "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    max_concurrent_runs = "20"
    max_daily_runs = "200"

    # Request Body
    endpoint_1_POST_request_body = r'''{}'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/quotas-v2/flows/{flows}/quota/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers,
        path_params={"flows": flows},
        query_params={
            "max_concurrent_runs": ["10"],
            "max_daily_runs": ["100"],
            "max_hourly_runs": max_concurrent_runs
        }
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 200

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/quotas-v2/flows/{flows}/quota/",
        method="GET",
        headers=headers,
        path_params={"flows": skyramp.get_response_value(endpoint_1_POST_response, "flow_id")}
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200

    # Request Body
    endpoint_1_PATCH_request_body = r'''{}'''
    
    # Execute Request
    endpoint_1_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/api/quotas-v2/flows/{flows}/quota/",
        method="PATCH",
        body=endpoint_1_PATCH_request_body,
        headers=headers,
        path_params={"flows": skyramp.get_response_value(endpoint_1_POST_response, "flow_id")},
        query_params={
            "max_concurrent_runs": skyramp.get_response_value(endpoint_1_POST_response, "max_hourly_runs"),
            "max_daily_runs": ["200"]
        }
    )
    # Generated Assertions
    assert endpoint_1_PATCH_response.status_code == 200


if __name__ == "__main__":
    test_integration()
