# Generated by Skyramp v1.3.14 on 2026-03-20 17:39:46.825542991 +0000 UTC m=+214.898958125
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output integration_trace_to_spans_workflow_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_trace-to-spans-workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_runs = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/traces-v2/flow-runs/{flow-runs}/trace/",
        method="GET",
        headers=headers,
        path_params={"flow-runs": flow_runs}
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/traces-v2/flow-runs/{flow-runs}/trace/{trace}/spans/",
        method="GET",
        headers=headers,
        path_params={
            "flow-runs": skyramp.get_response_value(endpoint_1_GET_response, "flow_run_id"),
            "trace": skyramp.get_response_value(endpoint_1_GET_response, "trace_id")
        }
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
