# Generated by Skyramp v1.3.14 on 2026-03-20 18:32:19.494193662 +0000 UTC m=+243.467463477
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output integration_flow_cost_profile_creation_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-cost-profile-creation.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    profiles_POST_request_body = r'''{}'''
    
    # Execute Request
    profiles_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/profiles",
        method="POST",
        body=profiles_POST_request_body,
        headers=headers,
        query_params={
            "cost_per_second": ["0.05"],
            "flow_id": ["flow-abc-001"]
        }
    )
    # Generated Assertions
    assert profiles_POST_response.status_code == 201


if __name__ == "__main__":
    test_integration()
