# Generated by Skyramp v1.3.13 on 2026-03-19 14:58:38.006196419 +0000 UTC m=+132.761990807
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_products-list-and-get.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    products_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/management/products",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert products_GET_response.status_code == 200

    # Execute Request
    products_products_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/management/products/{products}",
        method="GET",
        headers=headers,
        path_params={"products": skyramp.get_response_value(products_GET_response, "products.0.id")}
    )
    # Generated Assertions
    assert products_products_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
