# Generated by Skyramp v1.3.14 on 2026-03-20 17:52:45.340188784 +0000 UTC m=+235.731135521
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output integration_budget_boundary_validation_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_budget_boundary_validation.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    budgets_POST_request_body = r'''{
        "flow_id": "flow-boundary-test-001",
        "max_retries": 1
    }'''
    
    # Execute Request
    budgets_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/task-retries/budgets",
        method="POST",
        body=budgets_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert budgets_POST_response.status_code == 200

    # Execute Request
    budgets_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/task-retries/budgets",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert budgets_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
