# Generated by Skyramp v1.3.14 on 2026-03-20 18:59:10.218216299 +0000 UTC m=+206.689031065
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output integration_flow_cost_profile_crud.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow_cost_profile_crud_lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    flow_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "cost_per_second": 0.05,
        "cost_per_task": 0.1,
        "currency": "USD",
        "flow_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs-v2/profiles/",
        method="POST",
        body=endpoint_1_POST_request_body,
        data_override={"flow_id": flow_id}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 200

    # Execute Request
    flow_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs-v2/profiles/flow/{flow}",
        method="GET",
        path_params={"flow": flow_id}
    )
    # Generated Assertions
    assert flow_GET_response.status_code == 200

    # Request Body
    flow_PATCH_request_body = r'''{
        "cost_per_second": 0.08,
        "cost_per_task": 0.15
    }'''
    
    # Execute Request
    flow_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs-v2/profiles/flow/{flow}",
        method="PATCH",
        body=flow_PATCH_request_body,
        path_params={"flow": skyramp.get_response_value(flow_GET_response, "flow_id")}
    )
    # Generated Assertions
    assert flow_PATCH_response.status_code == 200

    # Execute Request
    flow_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs-v2/profiles/flow/{flow}",
        method="DELETE",
        path_params={"flow": skyramp.get_response_value(flow_GET_response, "flow_id")}
    )
    # Generated Assertions
    assert flow_DELETE_response.status_code == 200


if __name__ == "__main__":
    test_integration()
