# Generated by Skyramp v1.3.13 on 2026-03-19 10:41:32.958594049 +0000 UTC m=+113.341452197
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output integration_validation_status_health_check.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_validation-status-health-check-integration.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    health_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/validation-status/health",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert health_GET_response.status_code == 200

    # Execute Request
    check_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/validation-status/check",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert check_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
