# Generated by Skyramp v1.3.14 on 2026-03-20 17:29:44.353481546 +0000 UTC m=+173.361401019
# Command: skyramp generate contract rest http://localhost:4200/api/flow-quotas/limits \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-data {"limits":[{"flow_id":"flow-1","max_concurrent_runs":10,"max_daily_runs":100},{"flow_id":"flow-2","max_concurrent_runs":5,"max_daily_runs":50}]} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-quotas/limits GET
def test_limits_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_limits_GET_response_body = r'''{
        "limits": [
            {
                "flow_id": "flow-1",
                "max_concurrent_runs": 10,
                "max_daily_runs": 100
            },
            {
                "flow_id": "flow-2",
                "max_concurrent_runs": 5,
                "max_daily_runs": 50
            }
        ]
    }'''

    # Execute Request
    limits_GET_response = client.send_request(
        url=URL,
        path="/api/flow-quotas/limits",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(limits_GET_response, "20x")
    assert skyramp.check_schema(limits_GET_response, expected_limits_GET_response_body)
    assert skyramp.get_response_value(limits_GET_response, "limits.0.flow_id") is not None
    assert skyramp.get_response_value(limits_GET_response, "limits.0.max_concurrent_runs") is not None
    assert skyramp.get_response_value(limits_GET_response, "limits.0.max_daily_runs") is not None


if __name__ == "__main__":
    test_limits_get()
