# Generated by Skyramp v1.3.14 on 2026-03-20 18:30:57.525220393 +0000 UTC m=+95.556355395
# Command: skyramp generate contract rest http://localhost:4200/flow-quotas/limits \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"flow_id":"flow-1","max_concurrent_runs":10,"max_daily_runs":100} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /flow-quotas/limits POST
def test_limits_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    limits_POST_request_body = r'''{
        "flow_id": "flow-1",
        "max_concurrent_runs": 10,
        "max_daily_runs": 100
    }'''

    # Execute Request
    limits_POST_response = client.send_request(
        url=URL,
        path="/flow-quotas/limits",
        method="POST",
        body=limits_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(limits_POST_response, "20x")


if __name__ == "__main__":
    test_limits_post()
