# Generated by Skyramp v1.3.14 on 2026-03-20 18:31:03.038369111 +0000 UTC m=+101.069504093
# Command: skyramp generate contract rest http://localhost:4200/flow-quotas/limits \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /flow-quotas/limits GET
def test_limits_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    limits_GET_response = client.send_request(
        url=URL,
        path="/flow-quotas/limits",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(limits_GET_response, "20x")


if __name__ == "__main__":
    test_limits_get()
