# Generated by Skyramp v1.3.14 on 2026-03-20 17:53:31.040155429 +0000 UTC m=+260.240385315
# Command: skyramp generate contract rest http://localhost:4200/api/flow-impact/runs/{run_id}/notify \
# 		--auth-header Authorization \
# 		--consumer \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output notify_POST_consumer_contract_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params run_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--query-params impact_level=high \
# 		--response-data {"run_id":"3fa85f64-5717-4562-b3fc-2c963f66afa6","impact_level":"high","notifications_sent":3,"teams_notified":["team-a","team-b","team-c"]} \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp
from skyramp import MockV2


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-impact/runs/{run_id}/notify POST
def test_notify_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    run_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Expected Response Body
    expected_notify_POST_response_body = r'''{
        "impact_level": "high",
        "notifications_sent": 3,
        "run_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "teams_notified": [
            "team-a",
            "team-b",
            "team-c"
        ]
    }'''

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/flow-impact/runs/{run_id}/notify",
        method="POST",
        status_code=200,
        response_body=expected_notify_POST_response_body
    )
    client.apply_mock(mock)

    # Execute Request
    notify_POST_response = client.send_request(
        url=URL,
        path="/api/flow-impact/runs/{run_id}/notify",
        method="POST",
        headers=headers,
        path_params={"run_id": run_id},
        query_params={"impact_level": "high"}
    )

    # Generated Assertions
    assert skyramp.check_status_code(notify_POST_response, "20x")
    assert skyramp.check_schema(notify_POST_response, expected_notify_POST_response_body)
    assert skyramp.get_response_value(notify_POST_response, "impact_level") is not None
    assert skyramp.get_response_value(notify_POST_response, "notifications_sent") is not None
    assert skyramp.get_response_value(notify_POST_response, "run_id") is not None

    client.remove_all_mocks()


if __name__ == "__main__":
    test_notify_post()
