# Generated by Skyramp v1.3.14 on 2026-03-20 18:39:37.791187208 +0000 UTC m=+96.142974266
# Command: skyramp generate contract rest http://localhost:4200/api/flow-impact/runs/{run_id}/notify \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params run_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--query-params impact_level=critical \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-impact/runs/{run_id}/notify POST
def test_notify_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    run_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Expected Response Body
    expected_notify_POST_response_body = r'''{"run_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6", "impact_level": "critical", "notifications_sent": 3, "teams_notified": ["team-a", "team-b", "team-c"]}'''

    # Execute Request
    notify_POST_response = client.send_request(
        url=URL,
        path="/api/flow-impact/runs/{run_id}/notify",
        method="POST",
        headers=headers,
        path_params={"run_id": run_id},
        query_params={"impact_level": "critical"}
    )

    # Generated Assertions
    assert notify_POST_response.status_code == 200
    assert skyramp.check_schema(notify_POST_response, expected_notify_POST_response_body)


if __name__ == "__main__":
    test_notify_post()
