# Generated by Skyramp v1.3.14 on 2026-03-20 17:28:13.075377496 +0000 UTC m=+81.810914658
# Command: skyramp generate contract rest http://localhost:4200/api/flow-costs/profiles \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-costs/profiles GET
def test_profiles_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    profiles_GET_response = client.send_request(
        url=URL,
        path="/api/flow-costs/profiles",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(profiles_GET_response, "20x")


if __name__ == "__main__":
    test_profiles_get()
