# Generated by Skyramp v1.3.14 on 2026-03-20 17:47:33.877048017 +0000 UTC m=+204.482888275
# Command: skyramp generate contract rest http://localhost:4200/api/flow-costs/profiles \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"flow_id":"flow-test-123","cost_per_second":0.05} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-costs/profiles POST
def test_profiles_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    profiles_POST_request_body = r'''{
        "cost_per_second": 0.05,
        "flow_id": "flow-test-123"
    }'''

    # Execute Request
    profiles_POST_response = client.send_request(
        url=URL,
        path="/api/flow-costs/profiles",
        method="POST",
        body=profiles_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(profiles_POST_response, "20x")


if __name__ == "__main__":
    test_profiles_post()
