# Generated by Skyramp v1.3.14 on 2026-03-20 17:37:14.011679474 +0000 UTC m=+201.912998629
# Command: skyramp generate contract rest http://localhost:4200/api/flow-costs-v2/profiles/ \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"flow_id":"3fa85f64-5717-4562-b3fc-2c963f66afa6","cost_per_second":0.05,"cost_per_task":0.10,"currency":"USD"} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-costs-v2/profiles/ POST
def test_profiles_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    profiles_POST_request_body = r'''{
        "cost_per_second": 0.05,
        "cost_per_task": 0.1,
        "currency": "USD",
        "flow_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    }'''

    # Execute Request
    profiles_POST_response = client.send_request(
        url=URL,
        path="/api/flow-costs-v2/profiles/",
        method="POST",
        body=profiles_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(profiles_POST_response, "20x")


if __name__ == "__main__":
    test_profiles_post()
