# Generated by Skyramp v1.3.14 on 2026-03-20 18:09:37.088935757 +0000 UTC m=+175.619014070
# Command: skyramp generate contract rest http://localhost:4200/api/traces-v2/flow-runs/{flow_run_id}/trace/{trace_id}/spans/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output provider_contract_test_spans.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_run_id=3fa85f64-5717-4562-b3fc-2c963f66afa6,trace_id=7e3d91ac-8b2f-4c71-a5e6-1d9f8b3c0472 \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/traces-v2/flow-runs/{flow_run_id}/trace/{trace_id}/spans/ GET
def test_spans_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_run_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    trace_id = "7e3d91ac-8b2f-4c71-a5e6-1d9f8b3c0472"

    # Execute Request
    spans_GET_response = client.send_request(
        url=URL,
        path="/api/traces-v2/flow-runs/{flow_run_id}/trace/{trace_id}/spans/",
        method="GET",
        headers=headers,
        path_params={
            "flow_run_id": flow_run_id,
            "trace_id": trace_id
        }
    )

    # Generated Assertions
    assert skyramp.check_status_code(spans_GET_response, "20x")


if __name__ == "__main__":
    test_spans_get()
