# Generated by Skyramp v1.3.14 on 2026-03-20 17:39:16.810534655 +0000 UTC m=+184.883949782
# Command: skyramp generate contract rest http://localhost:4200/api/traces-v2/flow-runs/{flow_run_id}/trace/{trace_id}/spans/ \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_run_id=3fa85f64-5717-4562-b3fc-2c963f66afa6,trace_id=trace-456 \
# 		--provider \
# 		--response-data {"flow_run_id":"3fa85f64-5717-4562-b3fc-2c963f66afa6","trace_id":"trace-456","spans":[{"span_id":"span-1","name":"task-execution","duration_ms":150,"parent_span_id":null},{"span_id":"span-2","name":"data-processing","duration_ms":200,"parent_span_id":"span-1"}],"total_spans":2} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/traces-v2/flow-runs/{flow_run_id}/trace/{trace_id}/spans/ GET
def test_spans_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_run_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    trace_id = "trace-456"

    # Expected Response Body
    expected_spans_GET_response_body = r'''{
        "flow_run_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "spans": [
            {
                "duration_ms": 150,
                "name": "task-execution",
                "parent_span_id": null,
                "span_id": "span-1"
            },
            {
                "duration_ms": 200,
                "name": "data-processing",
                "parent_span_id": "span-1",
                "span_id": "span-2"
            }
        ],
        "total_spans": 2,
        "trace_id": "trace-456"
    }'''

    # Execute Request
    spans_GET_response = client.send_request(
        url=URL,
        path="/api/traces-v2/flow-runs/{flow_run_id}/trace/{trace_id}/spans/",
        method="GET",
        headers=headers,
        path_params={
            "flow_run_id": flow_run_id,
            "trace_id": trace_id
        }
    )

    # Generated Assertions
    assert skyramp.check_status_code(spans_GET_response, "20x")
    assert skyramp.check_schema(spans_GET_response, expected_spans_GET_response_body)
    assert skyramp.get_response_value(spans_GET_response, "flow_run_id") is not None
    assert skyramp.get_response_value(spans_GET_response, "spans.0.duration_ms") is not None
    assert skyramp.get_response_value(spans_GET_response, "spans.0.name") is not None


if __name__ == "__main__":
    test_spans_get()
