# Generated by Skyramp v1.3.14 on 2026-03-20 17:39:41.675243717 +0000 UTC m=+209.748658840
# Command: skyramp generate contract rest http://localhost:4200/api/traces-v2/flow-runs/{flow_run_id}/trace/ \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output provider_contract_trace_get_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_run_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--response-data {"flow_run_id":"3fa85f64-5717-4562-b3fc-2c963f66afa6","trace_id":"trace-456","started_at":"2026-03-20T14:00:00Z","duration_ms":5000,"span_count":15,"service_name":"prefect-server"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/traces-v2/flow-runs/{flow_run_id}/trace/ GET
def test_trace_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_run_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Expected Response Body
    expected_trace_GET_response_body = r'''{
        "duration_ms": 5000,
        "flow_run_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "service_name": "prefect-server",
        "span_count": 15,
        "started_at": "2026-03-20T14:00:00Z",
        "trace_id": "trace-456"
    }'''

    # Execute Request
    trace_GET_response = client.send_request(
        url=URL,
        path="/api/traces-v2/flow-runs/{flow_run_id}/trace/",
        method="GET",
        headers=headers,
        path_params={"flow_run_id": flow_run_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(trace_GET_response, "20x")
    assert skyramp.check_schema(trace_GET_response, expected_trace_GET_response_body)
    assert skyramp.get_response_value(trace_GET_response, "duration_ms") is not None
    assert skyramp.get_response_value(trace_GET_response, "flow_run_id") is not None
    assert skyramp.get_response_value(trace_GET_response, "service_name") is not None


if __name__ == "__main__":
    test_trace_get()
