# Generated by Skyramp v1.3.14 on 2026-03-22 20:23:17.949696342 +0000 UTC m=+235.056413761
# Command: skyramp generate contract rest http://localhost:4200/api/flow-costs-v2/flows/{flow_id}/cost-profile/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output provider_contract_test_cost_profile.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--response-data {"flow_id":"3fa85f64-5717-4562-b3fc-2c963f66afa6","cost_profile":{"id":"cp-3fa85f64-5717-4562-b3fc-2c963f66afa6","currency":"USD","cost_per_second":0.0001,"cost_per_task":0.05,"cost_per_gb_memory":0.0025,"fixed_cost_per_run":0.10},"current_spending":{"total_cost":45.75,"total_runs":150,"total_tasks":450,"total_duration_seconds":12500,"average_cost_per_run":0.305}} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-costs-v2/flows/{flow_id}/cost-profile/ GET
def test_cost_profile_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Expected Response Body
    expected_cost_profile_GET_response_body = r'''{
        "cost_profile": {
            "cost_per_gb_memory": 0.0025,
            "cost_per_second": 0.0001,
            "cost_per_task": 0.05,
            "currency": "USD",
            "fixed_cost_per_run": 0.1,
            "id": "cp-3fa85f64-5717-4562-b3fc-2c963f66afa6"
        },
        "current_spending": {
            "average_cost_per_run": 0.305,
            "total_cost": 45.75,
            "total_duration_seconds": 12500,
            "total_runs": 150,
            "total_tasks": 450
        },
        "flow_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    }'''

    # Execute Request
    cost_profile_GET_response = client.send_request(
        url=URL,
        path="/api/flow-costs-v2/flows/{flow_id}/cost-profile/",
        method="GET",
        headers=headers,
        path_params={"flow_id": flow_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(cost_profile_GET_response, "20x")
    assert skyramp.check_schema(cost_profile_GET_response, expected_cost_profile_GET_response_body)
    assert skyramp.get_response_value(cost_profile_GET_response, "cost_profile.cost_per_gb_memory") is not None
    assert skyramp.get_response_value(cost_profile_GET_response, "cost_profile.cost_per_second") is not None
    assert skyramp.get_response_value(cost_profile_GET_response, "cost_profile.cost_per_task") is not None


if __name__ == "__main__":
    test_cost_profile_get()
