# Generated by Skyramp v1.3.14 on 2026-03-20 18:12:17.603407007 +0000 UTC m=+245.539121352
# Command: skyramp generate contract rest http://localhost:4200/api/graph-v2/flows/{flow_id}/validate-graph/ \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output provider_contract_validate_graph_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--response-data {"flow_id":"3fa85f64-5717-4562-b3fc-2c963f66afa6","valid":true,"circular_dependencies":[],"unreachable_tasks":[],"warnings":[]} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/graph-v2/flows/{flow_id}/validate-graph/ POST
def test_validate_graph_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Expected Response Body
    expected_validate_graph_POST_response_body = r'''{
        "circular_dependencies": [],
        "flow_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "unreachable_tasks": [],
        "valid": true,
        "warnings": []
    }'''

    # Execute Request
    validate_graph_POST_response = client.send_request(
        url=URL,
        path="/api/graph-v2/flows/{flow_id}/validate-graph/",
        method="POST",
        headers=headers,
        path_params={"flow_id": flow_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(validate_graph_POST_response, "20x")
    assert skyramp.check_schema(validate_graph_POST_response, expected_validate_graph_POST_response_body)
    assert skyramp.get_response_value(validate_graph_POST_response, "circular_dependencies") is not None
    assert skyramp.get_response_value(validate_graph_POST_response, "flow_id") is not None
    assert skyramp.get_response_value(validate_graph_POST_response, "unreachable_tasks") is not None


if __name__ == "__main__":
    test_validate_graph_post()
