# Generated by Skyramp v1.3.14 on 2026-03-20 19:00:48.281584917 +0000 UTC m=+151.273633348
# Command: skyramp generate contract rest http://localhost:4200/traces-v2/flow-runs/{flow_run_id}/trace/ \
# 		--api-schema http://localhost:4200/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output provider_contract_traces_v2_trace_get_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_run_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /traces-v2/flow-runs/{flow_run_id}/trace/ GET
def test_trace_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_run_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Expected Response Body
    expected_trace_GET_response_body = r'''"string"'''

    # Execute Request
    trace_GET_response = client.send_request(
        url=URL,
        path="/traces-v2/flow-runs/{flow_run_id}/trace/",
        method="GET",
        headers=headers,
        path_params={"flow_run_id": flow_run_id}
    )

    # Generated Assertions
    assert trace_GET_response.status_code == 200
    assert skyramp.check_schema(trace_GET_response, expected_trace_GET_response_body)


if __name__ == "__main__":
    test_trace_get()
