# Generated by Skyramp v1.3.14 on 2026-03-22 21:13:34.124813748 +0000 UTC m=+185.097349928
# Command: skyramp generate contract rest http://127.0.0.1:4200/api/checkpoints-v2/flow-runs/{flow_run_id}/checkpoints/ \
# 		--api-schema http://127.0.0.1:4200/api/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_run_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--response-data {"id":"checkpoint-new","flow_run_id":"3fa85f64-5717-4562-b3fc-2c963f66afa6","name":"new_checkpoint","state":"active","created_at":"2026-03-20T10:00:00","metadata":{}} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

# contract test for /api/checkpoints-v2/flow-runs/{flow_run_id}/checkpoints/ POST
def test_checkpoints_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_run_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    checkpoints_POST_request_body = r'''{}'''

    # Expected Response Body
    expected_checkpoints_POST_response_body = r'''{
        "created_at": "2026-03-20T10:00:00",
        "flow_run_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "id": "checkpoint-new",
        "metadata": {},
        "name": "new_checkpoint",
        "state": "active"
    }'''

    # Execute Request
    checkpoints_POST_response = client.send_request(
        url=URL,
        path="/api/checkpoints-v2/flow-runs/{flow_run_id}/checkpoints/",
        method="POST",
        body=checkpoints_POST_request_body,
        headers=headers,
        path_params={"flow_run_id": flow_run_id}
    )

    # Generated Assertions
    assert checkpoints_POST_response.status_code == 200
    assert skyramp.check_schema(checkpoints_POST_response, expected_checkpoints_POST_response_body)
    assert skyramp.get_response_value(checkpoints_POST_response, "created_at") is not None
    assert skyramp.get_response_value(checkpoints_POST_response, "flow_run_id") is not None
    assert skyramp.get_response_value(checkpoints_POST_response, "id") is not None


if __name__ == "__main__":
    test_checkpoints_post()
