# Generated by Skyramp v1.3.14 on 2026-03-20 17:29:28.808970088 +0000 UTC m=+102.231318806
# Command: skyramp generate contract rest http://localhost:4200/flow-checkpoints/runs/{run_id}/restore \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params run_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--request-data {"checkpoint_id":"new-checkpoint"} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /flow-checkpoints/runs/{run_id}/restore POST
def test_restore_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    run_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    restore_POST_request_body = r'''{
        "checkpoint_id": "new-checkpoint"
    }'''

    # Execute Request
    restore_POST_response = client.send_request(
        url=URL,
        path="/flow-checkpoints/runs/{run_id}/restore",
        method="POST",
        body=restore_POST_request_body,
        headers=headers,
        path_params={"run_id": run_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(restore_POST_response, "20x")


if __name__ == "__main__":
    test_restore_post()
