# Generated by Skyramp v1.3.14 on 2026-03-20 17:52:37.974858513 +0000 UTC m=+180.257377855
# Command: skyramp generate contract rest http://localhost:4200/api/flow-costs-v2/run-costs/ \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output run_costs_POST_provider_contract_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"flow_run_id":"3fa85f64-5717-4562-b3fc-2c963f66afa6","total_cost":12.50,"execution_seconds":1250,"task_count":10,"cost_breakdown":{"compute":10.0,"storage":2.5}} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-costs-v2/run-costs/ POST
def test_run_costs_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    run_costs_POST_request_body = r'''{
        "cost_breakdown": {
            "compute": 10,
            "storage": 2.5
        },
        "execution_seconds": 1250,
        "flow_run_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "task_count": 10,
        "total_cost": 12.5
    }'''

    # Execute Request
    run_costs_POST_response = client.send_request(
        url=URL,
        path="/api/flow-costs-v2/run-costs/",
        method="POST",
        body=run_costs_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(run_costs_POST_response, "20x")


if __name__ == "__main__":
    test_run_costs_post()
