# Generated by Skyramp v1.3.14 on 2026-03-22 21:20:57.966134387 +0000 UTC m=+281.276823194
# Command: skyramp generate contract rest http://localhost:4200/api/flow-checkpoints/runs/{run_id} \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params run_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--query-params task_name=data-task-1,validation_status=invalid_value \
# 		--request-data {"step":1,"workflow_state":"running"} \
# 		--response-data {"detail":"validation_status must be one of: validated, pending, failed"} \
# 		--response-status-code 400 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-checkpoints/runs/{run_id} POST
def test_runs_run_id_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    run_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    runs_run_id_POST_request_body = r'''{
        "step": 1,
        "workflow_state": "running"
    }'''

    # Expected Response Body
    expected_runs_run_id_POST_response_body = r'''{
        "detail": "validation_status must be one of: validated, pending, failed"
    }'''

    # Execute Request
    runs_run_id_POST_response = client.send_request(
        url=URL,
        path="/api/flow-checkpoints/runs/{run_id}",
        method="POST",
        body=runs_run_id_POST_request_body,
        headers=headers,
        path_params={"run_id": run_id},
        query_params={
            "task_name": "data-task-1",
            "validation_status": "invalid_value"
        }
    )

    # Generated Assertions
    assert runs_run_id_POST_response.status_code == 400
    assert skyramp.check_schema(runs_run_id_POST_response, expected_runs_run_id_POST_response_body)
    assert skyramp.get_response_value(runs_run_id_POST_response, "detail") is not None


if __name__ == "__main__":
    test_runs_run_id_post()
