# Generated by Skyramp v1.3.14 on 2026-03-22 21:18:55.25095168 +0000 UTC m=+279.319895889
# Command: skyramp generate fuzz rest http://localhost:4200/api/flow-traces/runs/{run_id} \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params run_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--response-data {"run_id":"3fa85f64-5717-4562-b3fc-2c963f66afa6","trace_version":"2.0","spans":[{"span_id":"1","name":"task-1","duration_ms":150},{"span_id":"2","name":"task-2","duration_ms":200}],"total_duration_ms":350} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# fuzz test for /api/flow-traces/runs/{run_id} GET
def test_runs_run_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    run_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Execute Request
    runs_run_id_GET_response = client.send_request(
        url=URL,
        path="/api/flow-traces/runs/{run_id}",
        method="GET",
        headers=headers,
        path_params={"run_id": run_id},
        expected_code="20x"
    )

    assert client.is_success()


if __name__ == "__main__":
    test_runs_run_id_get()
