# Generated by Skyramp v1.3.14 on 2026-03-22 21:19:03.43676712 +0000 UTC m=+287.505711329
# Command: skyramp generate contract rest http://localhost:4200/api/flow-traces/runs/{run_id} \
# 		--consumer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params run_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--response-data {"run_id":"3fa85f64-5717-4562-b3fc-2c963f66afa6","trace_version":"2.0","spans":[{"span_id":"1","name":"task-1","duration_ms":150},{"span_id":"2","name":"task-2","duration_ms":200}],"total_duration_ms":350} \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp
from skyramp import MockV2


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-traces/runs/{run_id} GET
def test_runs_run_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    run_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Expected Response Body
    expected_runs_run_id_GET_response_body = r'''{
        "run_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "spans": [
            {
                "duration_ms": 150,
                "name": "task-1",
                "span_id": "1"
            },
            {
                "duration_ms": 200,
                "name": "task-2",
                "span_id": "2"
            }
        ],
        "total_duration_ms": 350,
        "trace_version": "2.0"
    }'''

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/flow-traces/runs/{run_id}",
        method="GET",
        status_code=200,
        response_body=expected_runs_run_id_GET_response_body
    )
    client.apply_mock(mock)

    # Execute Request
    runs_run_id_GET_response = client.send_request(
        url=URL,
        path="/api/flow-traces/runs/{run_id}",
        method="GET",
        headers=headers,
        path_params={"run_id": run_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(runs_run_id_GET_response, "20x")
    assert skyramp.check_schema(runs_run_id_GET_response, expected_runs_run_id_GET_response_body)
    assert skyramp.get_response_value(runs_run_id_GET_response, "run_id") is not None
    assert skyramp.get_response_value(runs_run_id_GET_response, "spans.0.duration_ms") is not None
    assert skyramp.get_response_value(runs_run_id_GET_response, "spans.0.name") is not None

    client.remove_all_mocks()


if __name__ == "__main__":
    test_runs_run_id_get()
