# Generated by Skyramp v1.3.14 on 2026-03-20 17:33:47.944167793 +0000 UTC m=+151.548144424
# Command: skyramp generate contract rest http://localhost:4200/api/task-validation/schemas \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"task_name":"process_data","schema_definition":{"type":"object","properties":{"result":{"type":"string"}}}} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/task-validation/schemas POST
def test_schemas_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    schemas_POST_request_body = r'''{
        "schema_definition": {
            "properties": {
                "result": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "task_name": "process_data"
    }'''

    # Execute Request
    schemas_POST_response = client.send_request(
        url=URL,
        path="/api/task-validation/schemas",
        method="POST",
        body=schemas_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(schemas_POST_response, "20x")


if __name__ == "__main__":
    test_schemas_post()
