# Generated by Skyramp v1.3.14 on 2026-03-20 17:49:41.684604814 +0000 UTC m=+133.770444329
# Command: skyramp generate fuzz rest http://localhost:4200/api/task-validation/schemas \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--request-data {"task_name":"process_data","schema_definition":{"type":"object","properties":{"result":{"type":"string"}}}} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# fuzz test for /api/task-validation/schemas POST
def test_schemas_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    schemas_POST_request_body = r'''{
      "task_name": "process_data",
      "schema_definition": {
        "type": "object",
        "properties": {
          "result": {
            "type": "string"
          }
        }
      }
    }'''
    
    # Fuzz strategies
    schemas_post_fuzzed_body = {
        "schema_definition": {
            "properties": {"result": {"type": "0123456789"}},
            "type": "0123456789"
        },
        "task_name": "0123456789"
    }
    # Fuzz status codes
    expected_schemas_post_status_code = {
        "schema_definition": {
            "properties": {"result": {"type": "40x"}},
            "type": "40x"
        },
        "task_name": "40x"
    }
    # Fuzz status codes for Null values
    expected_schemas_post_null_status_code = {
        "schema_definition": {
            "properties": {"result": {"type": "40x"}},
            "type": "40x"
        },
        "task_name": "40x"
    }

    # Execute Request
    schemas_POST_response = client.send_request(
        url=URL,
        path="/api/task-validation/schemas",
        method="POST",
        body=schemas_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(schemas_post_fuzzed_body):
        # Execute Request
        schemas_POST_response = client.send_request(
            url=URL,
            path="/api/task-validation/schemas",
            method="POST",
            body=schemas_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(schemas_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_schemas_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(schemas_post_fuzzed_body, key) }'
        )

        # Execute Request
        schemas_POST_response = client.send_request(
            url=URL,
            path="/api/task-validation/schemas",
            method="POST",
            body=schemas_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_schemas_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_schemas_post()
