# Generated by Skyramp v1.3.14 on 2026-03-22 21:18:59.496752724 +0000 UTC m=+283.565696963
# Command: skyramp generate fuzz rest http://localhost:4200/api/flow-traces/runs/{run_id}/spans \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params run_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--query-params span_name=data-validation-task,duration_ms=300 \
# 		--response-data {"run_id":"3fa85f64-5717-4562-b3fc-2c963f66afa6","span_id":"new-span","span_name":"data-validation-task","duration_ms":300} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# fuzz test for /api/flow-traces/runs/{run_id}/spans POST
def test_spans_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    run_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Fuzz strategies
    spans_post_fuzzed_query = {
        "duration_ms": "300",
        "span_name": "data-validation-task"
    }
    # Fuzz status codes
    expected_spans_post_fuzzed_query_status_code = {
        "duration_ms": "40x",
        "span_name": "40x"
    }

    # Execute Request
    spans_POST_response = client.send_request(
        url=URL,
        path="/api/flow-traces/runs/{run_id}/spans",
        method="POST",
        headers=headers,
        path_params={"run_id": run_id},
        query_params={
            "duration_ms": "300",
            "span_name": "data-validation-task"
        },
        expected_code="20x"
    )

    for key in spans_post_fuzzed_query:
        query_params = {
            "duration_ms": "300",
            "span_name": "data-validation-task"
        }

        query_params[key] = spans_post_fuzzed_query[key]

        # Execute Request
        spans_POST_response = client.send_request(
            url=URL,
            path="/api/flow-traces/runs/{run_id}/spans",
            method="POST",
            headers=headers,
            path_params={"run_id": run_id},
            query_params=query_params,
            expected_code=expected_spans_post_fuzzed_query_status_code[key],
            description=f'Fuzzing query param { key } to { spans_post_fuzzed_query[key] }'
        )

        query_params = {
            "duration_ms": "300",
            "span_name": "data-validation-task"
        }

        query_params[key] = ""

        # Execute Request
        spans_POST_response = client.send_request(
            url=URL,
            path="/api/flow-traces/runs/{run_id}/spans",
            method="POST",
            headers=headers,
            path_params={"run_id": run_id},
            query_params=query_params,
            expected_code=expected_spans_post_fuzzed_query_status_code[key],
            description=f'Fuzzing query param { key } to ""'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_spans_post()
