# Generated by Skyramp v1.3.14 on 2026-03-20 18:35:58.899314673 +0000 UTC m=+168.141385117
# Command: skyramp generate contract rest http://localhost:4200/api/flow-traces/runs/{run_id}/spans \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params run_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--query-params span_name=data-validation-task,duration_ms=300 \
# 		--response-data {"run_id":"3fa85f64-5717-4562-b3fc-2c963f66afa6","span_id":"new-span","span_name":"data-validation-task","duration_ms":300} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-traces/runs/{run_id}/spans POST
def test_spans_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    run_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Expected Response Body
    expected_spans_POST_response_body = r'''{
        "duration_ms": 300,
        "run_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "span_id": "new-span",
        "span_name": "data-validation-task"
    }'''

    # Execute Request
    spans_POST_response = client.send_request(
        url=URL,
        path="/api/flow-traces/runs/{run_id}/spans",
        method="POST",
        headers=headers,
        path_params={"run_id": run_id},
        query_params={
            "duration_ms": "300",
            "span_name": "data-validation-task"
        }
    )

    # Generated Assertions
    assert skyramp.check_status_code(spans_POST_response, "20x")
    assert skyramp.check_schema(spans_POST_response, expected_spans_POST_response_body)
    assert skyramp.get_response_value(spans_POST_response, "duration_ms") is not None
    assert skyramp.get_response_value(spans_POST_response, "run_id") is not None
    assert skyramp.get_response_value(spans_POST_response, "span_id") is not None


if __name__ == "__main__":
    test_spans_post()
