# Generated by Skyramp v1.3.14 on 2026-03-22 21:15:40.966748194 +0000 UTC m=+191.724592194
# Command: skyramp generate contract rest http://localhost:4200/api/task-validation-v2/task-runs/{task_run_id}/validation/ \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output task_validation_GET_provider_contract_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params task_run_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/task-validation-v2/task-runs/{task_run_id}/validation/ GET
def test_validation_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    task_run_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Execute Request
    validation_GET_response = client.send_request(
        url=URL,
        path="/api/task-validation-v2/task-runs/{task_run_id}/validation/",
        method="GET",
        headers=headers,
        path_params={"task_run_id": task_run_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(validation_GET_response, "20x")


if __name__ == "__main__":
    test_validation_get()
