# Generated by Skyramp v1.3.13 on 2026-03-16 22:37:51.7308676 +0000 UTC m=+150.765201329
# Command: skyramp generate contract rest http://localhost:4200/api/retry-budgets/flow-runs/00000000-0000-0000-0000-000000000003/retry-usage/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_contract_retry_usage_get.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/retry-budgets/flow-runs/00000000-0000-0000-0000-000000000003/retry-usage/ GET
def test_retry_usage_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    retry-usage_GET_response = client.send_request(
        url=URL,
        path="/api/retry-budgets/flow-runs/00000000-0000-0000-0000-000000000003/retry-usage/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(retry-usage_GET_response, "20x")


if __name__ == "__main__":
    test_retry_usage_get()
