# Generated by Skyramp v1.3.13 on 2026-03-16 21:33:34.090658451 +0000 UTC m=+175.137791797
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_run_trace_integration.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-run-trace-integration.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "name": "trace-test-flow",
        "tags": [
            "skyramp-test"
        ]
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201

    # Request Body
    _flow_id = skyramp.get_response_value(endpoint_2_POST_response, "id")
    endpoint_1_POST_request_body = f'{{"flow_id": "{_flow_id}", "name": "trace-test-flow-run", "state": {{"type": "SCHEDULED"}}}}'
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    endpoint_3_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/traces/flow-runs/{flow-runs}/trace/",
        method="GET",
        headers=headers,
        path_params={"flow-runs": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_3_GET_response.status_code == 404


if __name__ == "__main__":
    test_integration()
