# Generated by Skyramp v1.3.13 on 2026-03-16 21:36:07.285525134 +0000 UTC m=+153.144729788
# Command: skyramp generate fuzz rest http://localhost:4200/api/retry-budgets/flows/00000000-0000-0000-0000-000000000001/retry-budget/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_fuzz_retry_budget.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"flow_id":"00000000-0000-0000-0000-000000000001","max_total_retries":5,"retry_reset_interval_hours":12} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# fuzz test for /api/retry-budgets/flows/00000000-0000-0000-0000-000000000001/retry-budget/ POST
def test_retry_budget_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    retry-budget_POST_request_body = r'''{
      "flow_id": "00000000-0000-0000-0000-000000000001",
      "max_total_retries": 5,
      "retry_reset_interval_hours": 12
    }'''
    
    # Fuzz strategies
    retry_budget_post_fuzzed_body = {
        "flow_id": "0123456789",
        "max_total_retries": -10,
        "retry_reset_interval_hours": -10
    }
    # Fuzz status codes
    expected_retry_budget_post_status_code = {
        "flow_id": "40x",
        "max_total_retries": "40x",
        "retry_reset_interval_hours": "40x"
    }
    # Fuzz status codes for Null values
    expected_retry_budget_post_null_status_code = {
        "flow_id": "40x",
        "max_total_retries": "40x",
        "retry_reset_interval_hours": "40x"
    }

    # Execute Request
    retry-budget_POST_response = client.send_request(
        url=URL,
        path="/api/retry-budgets/flows/00000000-0000-0000-0000-000000000001/retry-budget/",
        method="POST",
        body=retry-budget_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(retry_budget_post_fuzzed_body):
        # Execute Request
        retry-budget_POST_response = client.send_request(
            url=URL,
            path="/api/retry-budgets/flows/00000000-0000-0000-0000-000000000001/retry-budget/",
            method="POST",
            body=retry-budget_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(retry_budget_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_retry_budget_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(retry_budget_post_fuzzed_body, key) }'
        )

        # Execute Request
        retry-budget_POST_response = client.send_request(
            url=URL,
            path="/api/retry-budgets/flows/00000000-0000-0000-0000-000000000001/retry-budget/",
            method="POST",
            body=retry-budget_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_retry_budget_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_retry_budget_post()
