# Generated by Skyramp v1.3.13 on 2026-03-16 18:50:40.373584305 +0000 UTC m=+170.128867272
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_cost_calculation_workflow.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-cost-calculation-workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_4_POST_request_body = r'''{
        "name": "cost-calc-flow-20240315",
        "tags": []
    }'''

    # Execute Request
    endpoint_4_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_4_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_4_POST_response.status_code == 201

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "cost_per_second": 0.01,
        "cost_per_task": 0.05,
        "currency": "USD",
        "flow_id": "aabbccdd-aabb-ccdd-aabb-aabbccddaabb"
    }'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/profiles/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers,
        data_override={"flow_id": skyramp.get_response_value(endpoint_4_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    endpoint_3_POST_request_body = r'''{
        "flow_id": "aabbccdd-aabb-ccdd-aabb-aabbccddaabb",
        "name": "cost-calc-flow-run-20240315"
    }'''

    # Execute Request
    endpoint_3_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-runs/",
        method="POST",
        body=endpoint_3_POST_request_body,
        headers=headers,
        data_override={"flow_id": skyramp.get_response_value(endpoint_4_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_3_POST_response.status_code == 201

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "calculated_at": "2024-03-15T00:05:00+00:00",
        "cost_breakdown": {
            "task_1": 0.65,
            "task_2": 0.65,
            "task_3": 0.65,
            "task_4": 0.65,
            "task_5": 0.65
        },
        "execution_seconds": 300,
        "flow_run_id": "ccddaabb-ccdd-aabb-ccdd-ccddaabbccdd",
        "task_count": 5,
        "total_cost": 3.25
    }'''

    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/run-costs/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers,
        data_override={"flow_run_id": skyramp.get_response_value(endpoint_3_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201

    # Execute Request
    flow_run_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/run-costs/flow-run/{flow-run}",
        method="GET",
        headers=headers,
        path_params={"flow-run": skyramp.get_response_value(endpoint_3_POST_response, "id")}
    )
    # Generated Assertions
    assert flow_run_GET_response.status_code == 200

    # Execute Request
    flow_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/history/flow/{flow}",
        method="GET",
        headers=headers,
        path_params={"flow": skyramp.get_response_value(endpoint_4_POST_response, "id")}
    )
    # Generated Assertions
    assert flow_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
