# Generated by Skyramp v1.3.13 on 2026-03-19 14:22:31.445096284 +0000 UTC m=+164.695305135
# Command: skyramp generate contract rest http://localhost:4200/api/management/products \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_management_products_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-data {"products":[{"id":1,"name":"Widget","price":9.99,"category":"tools"},{"id":2,"name":"Gadget","price":19.99,"category":"electronics"}],"total":2} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/management/products GET
def test_products_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_products_GET_response_body = r'''{
        "products": [
            {
                "category": "tools",
                "id": 1,
                "name": "Widget",
                "price": 9.99
            },
            {
                "category": "electronics",
                "id": 2,
                "name": "Gadget",
                "price": 19.99
            }
        ],
        "total": 2
    }'''

    # Execute Request
    products_GET_response = client.send_request(
        url=URL,
        path="/api/management/products",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(products_GET_response, "20x")
    assert skyramp.check_schema(products_GET_response, expected_products_GET_response_body)
    assert skyramp.get_response_value(products_GET_response, "products.0.category") is not None
    assert skyramp.get_response_value(products_GET_response, "products.0.id") is not None
    assert skyramp.get_response_value(products_GET_response, "products.0.name") is not None


if __name__ == "__main__":
    test_products_get()
