# Generated by Skyramp v1.3.13 on 2026-03-16 22:37:40.105384914 +0000 UTC m=+278.955421768
# Command: skyramp generate contract rest http://localhost:4200/api/quotas/flows/11111111-1111-1111-1111-111111111111/quota/ \
# 		--framework pytest \
# 		--language python \
# 		--method PATCH \
# 		--output test_quota_patch_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"max_concurrent_runs":3,"max_runs_per_hour":25,"max_runs_per_day":100,"quota_exceeded_action":"reject"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/quotas/flows/11111111-1111-1111-1111-111111111111/quota/ PATCH
def test_quota_patch():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    quota_PATCH_request_body = r'''{
        "max_concurrent_runs": 3,
        "max_runs_per_day": 100,
        "max_runs_per_hour": 25,
        "quota_exceeded_action": "reject"
    }'''

    # Execute Request
    quota_PATCH_response = client.send_request(
        url=URL,
        path="/api/quotas/flows/11111111-1111-1111-1111-111111111111/quota/",
        method="PATCH",
        body=quota_PATCH_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(quota_PATCH_response, "20x")


if __name__ == "__main__":
    test_quota_patch()
