# Generated by Skyramp v1.3.13 on 2026-03-16 22:02:53.4742151 +0000 UTC m=+240.646903306
# Command: skyramp generate fuzz rest http://localhost:4200/api/quotas/flows/11111111-1111-1111-1111-111111111111/quota/ \
# 		--framework pytest \
# 		--language python \
# 		--method PATCH \
# 		--output test_quota_patch_fuzz.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"max_concurrent_runs":5,"max_runs_per_hour":50,"max_runs_per_day":200,"quota_exceeded_action":"reject"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# fuzz test for /api/quotas/flows/11111111-1111-1111-1111-111111111111/quota/ PATCH
def test_quota_patch():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    quota_PATCH_request_body = r'''{
      "max_concurrent_runs": 5,
      "max_runs_per_hour": 50,
      "max_runs_per_day": 200,
      "quota_exceeded_action": "reject"
    }'''
    
    # Fuzz strategies
    quota_patch_fuzzed_body = {
        "max_concurrent_runs": -10,
        "max_runs_per_day": -10,
        "max_runs_per_hour": -10,
        "quota_exceeded_action": "0123456789"
    }
    # Fuzz status codes
    expected_quota_patch_status_code = {
        "max_concurrent_runs": "40x",
        "max_runs_per_day": "40x",
        "max_runs_per_hour": "40x",
        "quota_exceeded_action": "40x"
    }
    # Fuzz status codes for Null values
    expected_quota_patch_null_status_code = {
        "max_concurrent_runs": "40x",
        "max_runs_per_day": "40x",
        "max_runs_per_hour": "40x",
        "quota_exceeded_action": "40x"
    }

    # Execute Request
    quota_PATCH_response = client.send_request(
        url=URL,
        path="/api/quotas/flows/11111111-1111-1111-1111-111111111111/quota/",
        method="PATCH",
        body=quota_PATCH_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(quota_patch_fuzzed_body):
        # Execute Request
        quota_PATCH_response = client.send_request(
            url=URL,
            path="/api/quotas/flows/11111111-1111-1111-1111-111111111111/quota/",
            method="PATCH",
            body=quota_PATCH_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(quota_patch_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_quota_patch_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(quota_patch_fuzzed_body, key) }'
        )

        # Execute Request
        quota_PATCH_response = client.send_request(
            url=URL,
            path="/api/quotas/flows/11111111-1111-1111-1111-111111111111/quota/",
            method="PATCH",
            body=quota_PATCH_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_quota_patch_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_quota_patch()
