# Generated by Skyramp v1.3.13 on 2026-03-16 18:49:45.344931415 +0000 UTC m=+115.100214281
# Command: skyramp generate contract rest http://localhost:4200/api/flow-costs/run-costs/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_flow_run_cost_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"flow_run_id":"44444444-4444-4444-4444-444444444444","total_cost":5.25,"execution_seconds":300,"task_count":5,"cost_breakdown":{"task_1":0.5,"task_2":0.75,"task_3":1.0,"task_4":1.25,"task_5":1.75},"calculated_at":"2024-01-01T00:05:00+00:00"} \
# 		--response-status-code 201 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-costs/run-costs/ POST
def test_run_costs_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    run-costs_POST_request_body = r'''{
        "calculated_at": "2024-01-01T00:05:00+00:00",
        "cost_breakdown": {
            "task_1": 0.5,
            "task_2": 0.75,
            "task_3": 1,
            "task_4": 1.25,
            "task_5": 1.75
        },
        "execution_seconds": 300,
        "flow_run_id": "44444444-4444-4444-4444-444444444444",
        "task_count": 5,
        "total_cost": 5.25
    }'''

    # Execute Request
    run-costs_POST_response = client.send_request(
        url=URL,
        path="/api/flow-costs/run-costs/",
        method="POST",
        body=run-costs_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert run-costs_POST_response.status_code == 201


if __name__ == "__main__":
    test_run_costs_post()
