# Generated by Skyramp v1.3.13 on 2026-03-16 18:07:58.44423965 +0000 UTC m=+214.632331196
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_cost_profile_lifecycle.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-cost-profile-lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "name": "cost-tracking-flow-20240101",
        "tags": []
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "cost_per_second": 0.01,
        "cost_per_task": 0.05,
        "currency": "USD",
        "flow_id": "11111111-1111-1111-1111-111111111111"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/profiles/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers,
        data_override={"flow_id": skyramp.get_response_value(endpoint_2_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    flow_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/profiles/flow/{flow}",
        method="GET",
        headers=headers,
        path_params={"flow": skyramp.get_response_value(endpoint_2_POST_response, "id")}
    )
    # Generated Assertions
    assert flow_GET_response.status_code == 200

    # Request Body
    flow_PATCH_request_body = r'''{
        "cost_per_second": 0.02,
        "cost_per_task": 0.1,
        "currency": "USD"
    }'''
    
    # Execute Request
    flow_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/profiles/flow/{flow}",
        method="PATCH",
        body=flow_PATCH_request_body,
        headers=headers,
        path_params={"flow": skyramp.get_response_value(endpoint_2_POST_response, "id")},
        data_override={"currency": skyramp.get_response_value(flow_GET_response, "currency")}
    )
    # Generated Assertions
    assert flow_PATCH_response.status_code == 204

    # Execute Request
    flow_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/profiles/flow/{flow}",
        method="DELETE",
        headers=headers,
        path_params={"flow": skyramp.get_response_value(endpoint_2_POST_response, "id")}
    )
    # Generated Assertions
    assert flow_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
