# Generated by Skyramp v1.3.13 on 2026-03-16 21:36:07.249151981 +0000 UTC m=+153.108356635
# Command: skyramp generate contract rest http://localhost:4200/api/retry-budgets/flows/00000000-0000-0000-0000-000000000001/retry-budget/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_contract_retry_budget_create.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"flow_id":"00000000-0000-0000-0000-000000000001","max_total_retries":5,"retry_reset_interval_hours":12} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/retry-budgets/flows/00000000-0000-0000-0000-000000000001/retry-budget/ POST
def test_retry_budget_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    retry-budget_POST_request_body = r'''{
        "flow_id": "00000000-0000-0000-0000-000000000001",
        "max_total_retries": 5,
        "retry_reset_interval_hours": 12
    }'''

    # Execute Request
    retry-budget_POST_response = client.send_request(
        url=URL,
        path="/api/retry-budgets/flows/00000000-0000-0000-0000-000000000001/retry-budget/",
        method="POST",
        body=retry-budget_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(retry-budget_POST_response, "20x")


if __name__ == "__main__":
    test_retry_budget_post()
