# Generated by Skyramp v1.3.13 on 2026-03-16 21:15:14.51083279 +0000 UTC m=+179.223977515
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_quota_usage_workflow.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-quota-usage-workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_id = "33333333-3333-3333-3333-333333333333"

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "labels": {},
        "name": "quota-usage-test-flow-5678",
        "tags": []
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "flow_id": "33333333-3333-3333-3333-333333333333",
        "max_concurrent_runs": 3,
        "max_runs_per_day": 100,
        "max_runs_per_hour": 20,
        "quota_exceeded_action": "reject"
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/quotas/flows/{flows}/quota/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers,
        path_params={"flows": skyramp.get_response_value(endpoint_1_POST_response, "id")},
        data_override={"flow_id": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201

    # Execute Request
    endpoint_4_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/quotas/flows/{flows}/quota/usage/",
        method="GET",
        headers=headers,
        path_params={"flows": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_4_GET_response.status_code == 200

    # Request Body
    endpoint_3_POST_request_body = r'''{}'''
    
    # Execute Request
    endpoint_3_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/quotas/flows/{flows}/quota/reset/",
        method="POST",
        body=endpoint_3_POST_request_body,
        headers=headers,
        path_params={"flows": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_3_POST_response.status_code == 201


if __name__ == "__main__":
    test_integration()
