# Generated by Skyramp v1.3.13 on 2026-03-19 14:40:24.321169851 +0000 UTC m=+129.990318977
# Command: skyramp generate contract rest http://localhost:4200/api/management/products/1 \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_management_products_by_id_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-data {"id":1,"name":"Product 1","price":29.99,"category":"general","in_stock":true} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/management/products/1 GET
def test_endpoint_1_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_endpoint_1_GET_response_body = r'''{
        "category": "general",
        "id": 1,
        "in_stock": true,
        "name": "Product 1",
        "price": 29.99
    }'''

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL,
        path="/api/management/products/1",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(endpoint_1_GET_response, "20x")
    assert skyramp.check_schema(endpoint_1_GET_response, expected_endpoint_1_GET_response_body)
    assert skyramp.get_response_value(endpoint_1_GET_response, "category") is not None
    assert skyramp.get_response_value(endpoint_1_GET_response, "id") is not None
    assert skyramp.get_response_value(endpoint_1_GET_response, "in_stock") is not None


if __name__ == "__main__":
    test_endpoint_1_get()
