# Generated by Skyramp v1.3.13 on 2026-03-19 14:24:27.962424119 +0000 UTC m=+281.212632976
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_management_users_list_and_get.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_users-list-and-get.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    users_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/management/users",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert users_GET_response.status_code == 200

    # Execute Request
    users_users_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/management/users/{users}",
        method="GET",
        headers=headers,
        path_params={"users": skyramp.get_response_value(users_GET_response, "users.0.id")}
    )
    # Generated Assertions
    assert users_users_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
