# Generated by Skyramp v1.3.13 on 2026-03-16 21:38:38.041848239 +0000 UTC m=+238.123743524
# Command: skyramp generate fuzz rest http://localhost:4200/api/impact/flows/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa/dependencies/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_flow_dependency_fuzz.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"upstream_flow_id":"aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa","downstream_flow_id":"bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb","dependency_type":"triggers"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# fuzz test for /api/impact/flows/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa/dependencies/ POST
def test_dependencies_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    dependencies_POST_request_body = r'''{
      "upstream_flow_id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
      "downstream_flow_id": "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
      "dependency_type": "triggers"
    }'''
    
    # Fuzz strategies
    dependencies_post_fuzzed_body = {
        "dependency_type": "0123456789",
        "downstream_flow_id": "0123456789",
        "upstream_flow_id": "0123456789"
    }
    # Fuzz status codes
    expected_dependencies_post_status_code = {
        "dependency_type": "40x",
        "downstream_flow_id": "40x",
        "upstream_flow_id": "40x"
    }
    # Fuzz status codes for Null values
    expected_dependencies_post_null_status_code = {
        "dependency_type": "40x",
        "downstream_flow_id": "40x",
        "upstream_flow_id": "40x"
    }

    # Execute Request
    dependencies_POST_response = client.send_request(
        url=URL,
        path="/api/impact/flows/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa/dependencies/",
        method="POST",
        body=dependencies_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(dependencies_post_fuzzed_body):
        # Execute Request
        dependencies_POST_response = client.send_request(
            url=URL,
            path="/api/impact/flows/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa/dependencies/",
            method="POST",
            body=dependencies_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(dependencies_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_dependencies_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(dependencies_post_fuzzed_body, key) }'
        )

        # Execute Request
        dependencies_POST_response = client.send_request(
            url=URL,
            path="/api/impact/flows/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa/dependencies/",
            method="POST",
            body=dependencies_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_dependencies_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_dependencies_post()
