# Generated by Skyramp v1.3.13 on 2026-03-16 18:07:58.496697177 +0000 UTC m=+214.684788869
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_run_cost_calculation.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-run-cost-calculation.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_3_POST_request_body = r'''{
        "name": "run-cost-flow-20240101",
        "tags": []
    }'''
    
    # Execute Request
    endpoint_3_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_3_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_3_POST_response.status_code == 201

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "flow_id": "33333333-3333-3333-3333-333333333333",
        "name": "run-cost-flow-run-20240101"
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-runs/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers,
        data_override={"flow_id": skyramp.get_response_value(endpoint_3_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "calculated_at": "2024-01-01T00:05:00+00:00",
        "cost_breakdown": {
            "task_1": 0.5,
            "task_2": 0.75,
            "task_3": 1,
            "task_4": 1.25,
            "task_5": 1.75
        },
        "execution_seconds": 300,
        "flow_run_id": "44444444-4444-4444-4444-444444444444",
        "task_count": 5,
        "total_cost": 5.25
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/run-costs/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers,
        data_override={"flow_run_id": skyramp.get_response_value(endpoint_2_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    flow_run_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/run-costs/flow-run/{flow-run}",
        method="GET",
        headers=headers,
        path_params={"flow-run": skyramp.get_response_value(endpoint_2_POST_response, "id")}
    )
    # Generated Assertions
    assert flow_run_GET_response.status_code == 200

    # Execute Request
    flow_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/history/flow/{flow}",
        method="GET",
        headers=headers,
        path_params={"flow": skyramp.get_response_value(endpoint_3_POST_response, "id")}
    )
    # Generated Assertions
    assert flow_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
