# Generated by Skyramp v1.3.13 on 2026-03-16 22:37:55.644086859 +0000 UTC m=+153.344204917
# Command: skyramp generate contract rest http://localhost:4200/api/impact/flow-runs/cccccccc-cccc-cccc-cccc-cccccccccccc/impact-analysis/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_impact_analysis_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/impact/flow-runs/cccccccc-cccc-cccc-cccc-cccccccccccc/impact-analysis/ GET
def test_impact_analysis_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    impact_analysis_GET_response = client.send_request(
        url=URL,
        path="/api/impact/flow-runs/cccccccc-cccc-cccc-cccc-cccccccccccc/impact-analysis/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(impact_analysis_GET_response, "20x")


if __name__ == "__main__":
    test_impact_analysis_get()
