# Generated by Skyramp v1.3.14 on 2026-03-20 17:38:08.951341348 +0000 UTC m=+256.852660493
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_cost_profile_lifecycle.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-cost-profile-lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    cost_per_second = "0.08"
    cost_per_task = "0.15"
    flow_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    endpoint_1_POST_request_body = r'''{}'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs-v2/profiles/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers,
        query_params={
            "cost_per_second": ["0.05"],
            "cost_per_task": ["0.1"],
            "currency": ["USD"],
            "flow_id": flow_id
        }
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    flow_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs-v2/profiles/flow/{flow}",
        method="GET",
        headers=headers,
        path_params={"flow": skyramp.get_response_value(endpoint_1_POST_response, "flow_id")}
    )
    # Generated Assertions
    assert flow_GET_response.status_code == 200

    # Request Body
    flow_PATCH_request_body = r'''{}'''
    
    # Execute Request
    flow_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs-v2/profiles/flow/{flow}",
        method="PATCH",
        body=flow_PATCH_request_body,
        headers=headers,
        path_params={"flow": skyramp.get_response_value(endpoint_1_POST_response, "flow_id")},
        query_params={
            "cost_per_second": ["0.08"],
            "cost_per_task": ["0.15"]
        }
    )
    # Generated Assertions
    assert flow_PATCH_response.status_code == 200

    # Execute Request
    flow_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs-v2/profiles/flow/{flow}",
        method="DELETE",
        headers=headers,
        path_params={"flow": skyramp.get_response_value(endpoint_1_POST_response, "flow_id")}
    )
    # Generated Assertions
    assert flow_DELETE_response.status_code == 200


if __name__ == "__main__":
    test_integration()
