# Generated by Skyramp v1.3.13 on 2026-03-16 18:08:09.747442037 +0000 UTC m=+225.935533599
# Command: skyramp generate fuzz rest http://localhost:4200/api/flow-costs/run-costs/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_flow_run_cost_fuzz.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"flow_run_id":"44444444-4444-4444-4444-444444444444","total_cost":5.25,"execution_seconds":300,"task_count":5,"cost_breakdown":{"task_1":0.50},"calculated_at":"2024-01-01T00:05:00+00:00"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# fuzz test for /api/flow-costs/run-costs/ POST
def test_run_costs_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    run-costs_POST_request_body = r'''{
      "flow_run_id": "44444444-4444-4444-4444-444444444444",
      "total_cost": 5.25,
      "execution_seconds": 300,
      "task_count": 5,
      "cost_breakdown": {
        "task_1": 0.50
      },
      "calculated_at": "2024-01-01T00:05:00+00:00"
    }'''
    
    # Fuzz strategies
    run_costs_post_fuzzed_body = {
        "calculated_at": "0123456789",
        "cost_breakdown": {"task_1": -10},
        "execution_seconds": -10,
        "flow_run_id": "0123456789",
        "task_count": -10,
        "total_cost": -10
    }
    # Fuzz status codes
    expected_run_costs_post_status_code = {
        "calculated_at": "40x",
        "cost_breakdown": {"task_1": "40x"},
        "execution_seconds": "40x",
        "flow_run_id": "40x",
        "task_count": "40x",
        "total_cost": "40x"
    }
    # Fuzz status codes for Null values
    expected_run_costs_post_null_status_code = {
        "calculated_at": "40x",
        "cost_breakdown": {"task_1": "40x"},
        "execution_seconds": "40x",
        "flow_run_id": "40x",
        "task_count": "40x",
        "total_cost": "40x"
    }

    # Execute Request
    run-costs_POST_response = client.send_request(
        url=URL,
        path="/api/flow-costs/run-costs/",
        method="POST",
        body=run-costs_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(run_costs_post_fuzzed_body):
        # Execute Request
        run-costs_POST_response = client.send_request(
            url=URL,
            path="/api/flow-costs/run-costs/",
            method="POST",
            body=run-costs_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(run_costs_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_run_costs_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(run_costs_post_fuzzed_body, key) }'
        )

        # Execute Request
        run-costs_POST_response = client.send_request(
            url=URL,
            path="/api/flow-costs/run-costs/",
            method="POST",
            body=run-costs_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_run_costs_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_run_costs_post()
