# Generated by Skyramp v1.3.13 on 2026-03-19 14:23:36.903348614 +0000 UTC m=+230.153557470
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_management_users_lifecycle.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_users-crud-lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    users_POST_request_body = r'''{
        "email": "alice@example.com",
        "name": "Alice Smith"
    }'''
    
    # Execute Request
    users_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/management/users",
        method="POST",
        body=users_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert users_POST_response.status_code == 200

    # Execute Request
    users_users_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/management/users/{users}",
        method="GET",
        headers=headers,
        path_params={"users": skyramp.get_response_value(users_POST_response, "id")}
    )
    # Generated Assertions
    assert users_users_GET_response.status_code == 200

    # Request Body
    users_POST_1_request_body = r'''{}'''
    
    # Execute Request
    users_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/management/users",
        method="POST",
        body=users_POST_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert users_POST_1_response.status_code == 200

    # Execute Request
    users_users_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/management/users/{users}",
        method="GET",
        headers=headers,
        path_params={"users": skyramp.get_response_value(users_POST_response, "id")}
    )
    # Generated Assertions
    assert users_users_GET_1_response.status_code == 200


if __name__ == "__main__":
    test_integration()
