# Generated by Skyramp v1.3.13 on 2026-03-20 14:12:34.814896291 +0000 UTC m=+218.868533947
# Command: skyramp generate contract rest http://localhost:4200/health/readiness \
# 		--consumer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_health_readiness_consumer_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-data {"ready":true,"checks":{"database":"ok","api":"ok"}} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import os
import pytest
import skyramp
import requests
from skyramp import MockV2


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /health/readiness GET
def test_health_readiness_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_health_readiness_GET_response_body = r'''{
        "checks": {
            "api": "ok",
            "database": "ok"
        },
        "ready": true
    }'''

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/health/readiness",
        method="GET",
        status_code=200,
        response_body=expected_health_readiness_GET_response_body
    )
    client.apply_mock(mock)

    # Execute Request
    health_readiness_GET_response = client.send_request(
        url=URL,
        path="/health/readiness",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(health_readiness_GET_response, "20x")
    assert skyramp.check_schema(health_readiness_GET_response, expected_health_readiness_GET_response_body)
    assert skyramp.get_response_value(health_readiness_GET_response, "checks.api") is not None
    assert skyramp.get_response_value(health_readiness_GET_response, "checks.database") is not None
    assert skyramp.get_response_value(health_readiness_GET_response, "ready") is not None

    client.remove_all_mocks()


if __name__ == "__main__":
    test_health_readiness_get()
