# Generated by Skyramp v1.3.14 on 2026-03-20 17:37:40.830651794 +0000 UTC m=+228.731970960
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_cost_auth_boundary.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-cost-auth-boundary.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{}'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs-v2/profiles/",
        method="POST",
        body=endpoint_1_POST_request_body,
        query_params={
            "cost_per_second": ["0.05"],
            "flow_id": ["3fa85f64-5717-4562-b3fc-2c963f66afa6"]
        }
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 401


if __name__ == "__main__":
    test_integration()
