# Generated by Skyramp v1.3.13 on 2026-03-20 14:12:33.083222274 +0000 UTC m=+217.136859919
# Command: skyramp generate contract rest http://localhost:4200/health/status \
# 		--consumer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_health_status_consumer_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-data {"status":"healthy","version":"2.0.0","service":"prefect-server"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import os
import pytest
import skyramp
import requests
from skyramp import MockV2


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /health/status GET
def test_health_status_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_health_status_GET_response_body = r'''{
        "service": "prefect-server",
        "status": "healthy",
        "version": "2.0.0"
    }'''

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/health/status",
        method="GET",
        status_code=200,
        response_body=expected_health_status_GET_response_body
    )
    client.apply_mock(mock)

    # Execute Request
    health_status_GET_response = client.send_request(
        url=URL,
        path="/health/status",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(health_status_GET_response, "20x")
    assert skyramp.check_schema(health_status_GET_response, expected_health_status_GET_response_body)
    assert skyramp.get_response_value(health_status_GET_response, "service") is not None
    assert skyramp.get_response_value(health_status_GET_response, "status") is not None
    assert skyramp.get_response_value(health_status_GET_response, "version") is not None

    client.remove_all_mocks()


if __name__ == "__main__":
    test_health_status_get()
