# Generated by Skyramp v1.3.13 on 2026-03-20 14:13:18.886708824 +0000 UTC m=+262.940346459
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_health_response_values_integration.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_health-response-values.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Execute Request
    status_GET_response = client.send_request(
        url=URL_localhost,
        path="/health/status",
        method="GET"
    )
    # Generated Assertions
    assert status_GET_response.status_code == 200

    # Execute Request
    readiness_GET_response = client.send_request(
        url=URL_localhost,
        path="/health/readiness",
        method="GET"
    )
    # Generated Assertions
    assert readiness_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
