# Generated by Skyramp v1.3.13 on 2026-03-16 21:35:42.367378454 +0000 UTC m=+128.226583108
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_retry_budget_lifecycle.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-retry-budget-lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "name": "test-retry-budget-flow"
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201

    # Request Body
    endpoint_4_POST_request_body = r'''{
        "flow_id": "00000000-0000-0000-0000-000000000001",
        "max_total_retries": 5,
        "retry_reset_interval_hours": 12
    }'''
    
    # Execute Request
    endpoint_4_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/retry-budgets/flows/{flows}/retry-budget/",
        method="POST",
        body=endpoint_4_POST_request_body,
        headers=headers,
        path_params={"flows": skyramp.get_response_value(endpoint_2_POST_response, "id")},
        data_override={"flow_id": skyramp.get_response_value(endpoint_2_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_4_POST_response.status_code == 201

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "flow_id": "00000000-0000-0000-0000-000000000001",
        "name": "test-retry-flow-run-1"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers,
        data_override={"flow_id": skyramp.get_response_value(endpoint_2_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    endpoint_3_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/retry-budgets/flow-runs/{flow-runs}/retry-usage/",
        method="GET",
        headers=headers,
        path_params={"flow-runs": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_3_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
