# Generated by Skyramp v1.3.13 on 2026-03-16 22:37:25.488484227 +0000 UTC m=+127.575867364
# Command: skyramp generate fuzz rest http://localhost:4200/api/checkpoints/flow-runs/00000000-0000-0000-0000-000000000001/checkpoints/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_checkpoints_fuzz.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_run_id=00000000-0000-0000-0000-000000000001 \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# fuzz test for /api/checkpoints/flow-runs/00000000-0000-0000-0000-000000000001/checkpoints/ GET
def test_checkpoints_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    checkpoints_GET_response = client.send_request(
        url=URL,
        path="/api/checkpoints/flow-runs/00000000-0000-0000-0000-000000000001/checkpoints/",
        method="GET",
        headers=headers,
        expected_code="20x"
    )

    assert client.is_success()


if __name__ == "__main__":
    test_checkpoints_get()
