# Generated by Skyramp v1.3.13 on 2026-03-16 21:40:11.365887236 +0000 UTC m=+331.447782521
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_impact_analysis_integration.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-impact-analysis-workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "name": "upstream-etl-flow",
        "tags": [
            "upstream",
            "etl"
        ]
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201

    # Request Body
    endpoint_2_POST_1_request_body = r'''{
        "name": "downstream-reporting-flow",
        "tags": [
            "downstream",
            "reporting"
        ]
    }'''
    
    # Execute Request
    endpoint_2_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_2_POST_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_1_response.status_code == 201

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "flow_id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
        "name": "upstream-etl-flow-run-1",
        "tags": [
            "test"
        ]
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-runs/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers,
        data_override={"flow_id": skyramp.get_response_value(endpoint_2_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    endpoint_4_POST_request_body = r'''{
        "dependency_type": "triggers",
        "downstream_flow_id": "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
        "upstream_flow_id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"
    }'''
    
    # Execute Request
    endpoint_4_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/impact/flows/{flows}/dependencies/",
        method="POST",
        body=endpoint_4_POST_request_body,
        headers=headers,
        path_params={"flows": skyramp.get_response_value(endpoint_2_POST_response, "id")},
        data_override={"upstream_flow_id": skyramp.get_response_value(endpoint_2_POST_response, "id"), "downstream_flow_id": skyramp.get_response_value(endpoint_2_POST_1_response, "id")}
    )
    # Generated Assertions
    assert endpoint_4_POST_response.status_code == 200

    # Execute Request
    endpoint_3_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/impact/flow-runs/{flow-runs}/impact-analysis/",
        method="GET",
        headers=headers,
        path_params={"flow-runs": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_3_GET_response.status_code == 200

    # Execute Request
    endpoint_5_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/impact/flows/{flows}/dependency-graph/",
        method="GET",
        headers=headers,
        path_params={"flows": skyramp.get_response_value(endpoint_2_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_5_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
