# Generated by Skyramp v1.3.13 on 2026-03-16 22:37:40.182014129 +0000 UTC m=+279.032050973
# Command: skyramp generate fuzz rest http://localhost:4200/api/quotas/flows/11111111-1111-1111-1111-111111111111/quota/ \
# 		--framework pytest \
# 		--language python \
# 		--method DELETE \
# 		--output test_quota_delete_fuzz.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# fuzz test for /api/quotas/flows/11111111-1111-1111-1111-111111111111/quota/ DELETE
def test_quota_delete():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    quota_DELETE_response = client.send_request(
        url=URL,
        path="/api/quotas/flows/11111111-1111-1111-1111-111111111111/quota/",
        method="DELETE",
        headers=headers,
        expected_code="20x"
    )

    assert client.is_success()


if __name__ == "__main__":
    test_quota_delete()
