# Generated by Skyramp v1.3.13 on 2026-03-16 22:38:00.268485388 +0000 UTC m=+157.968603447
# Command: skyramp generate contract rest http://localhost:4200/api/impact/flows/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa/dependency-graph/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_dependency_graph_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/impact/flows/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa/dependency-graph/ GET
def test_dependency_graph_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    dependency_graph_GET_response = client.send_request(
        url=URL,
        path="/api/impact/flows/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa/dependency-graph/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(dependency_graph_GET_response, "20x")


if __name__ == "__main__":
    test_dependency_graph_get()
