# Generated by Skyramp v1.3.14 on 2026-03-20 17:41:24.976656149 +0000 UTC m=+276.954862104
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_graph_v2_dependency_workflow.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_graph-v2-dependency-workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    flows = "a1b2c3d4-5617-4abc-b3fc-2c963f66bcd5"

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/graph-v2/flows/{flows}/graph-analysis/",
        method="GET",
        path_params={"flows": flows}
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200

    # Request Body
    endpoint_2_POST_request_body = r'''{}'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/graph-v2/flows/{flows}/validate-graph/",
        method="POST",
        body=endpoint_2_POST_request_body,
        path_params={"flows": skyramp.get_response_value(endpoint_1_GET_response, "flow_id")}
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 200


if __name__ == "__main__":
    test_integration()
