# Generated by Skyramp v1.3.13 on 2026-03-16 18:08:09.686533689 +0000 UTC m=+225.874625240
# Command: skyramp generate contract rest http://localhost:4200/api/flow-costs/profiles/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_flow_cost_profile_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"flow_id":"11111111-1111-1111-1111-111111111111","cost_per_second":0.01,"cost_per_task":0.05,"currency":"USD"} \
# 		--response-status-code 201 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-costs/profiles/ POST
def test_profiles_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    profiles_POST_request_body = r'''{
        "cost_per_second": 0.01,
        "cost_per_task": 0.05,
        "currency": "USD",
        "flow_id": "11111111-1111-1111-1111-111111111111"
    }'''

    # Execute Request
    profiles_POST_response = client.send_request(
        url=URL,
        path="/api/flow-costs/profiles/",
        method="POST",
        body=profiles_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert profiles_POST_response.status_code == 201


if __name__ == "__main__":
    test_profiles_post()
