# Generated by Skyramp v1.3.13 on 2026-03-16 21:15:24.200383022 +0000 UTC m=+188.913527745
# Command: skyramp generate contract rest http://localhost:4200/api/quotas/flows/11111111-1111-1111-1111-111111111111/quota/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_quota_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"flow_id":"11111111-1111-1111-1111-111111111111","max_concurrent_runs":5,"max_runs_per_hour":50,"max_runs_per_day":200,"quota_exceeded_action":"reject"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/quotas/flows/11111111-1111-1111-1111-111111111111/quota/ POST
def test_quota_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    quota_POST_request_body = r'''{
        "flow_id": "11111111-1111-1111-1111-111111111111",
        "max_concurrent_runs": 5,
        "max_runs_per_day": 200,
        "max_runs_per_hour": 50,
        "quota_exceeded_action": "reject"
    }'''

    # Execute Request
    quota_POST_response = client.send_request(
        url=URL,
        path="/api/quotas/flows/11111111-1111-1111-1111-111111111111/quota/",
        method="POST",
        body=quota_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(quota_POST_response, "20x")


if __name__ == "__main__":
    test_quota_post()
