# Generated by Skyramp v1.3.13 on 2026-03-16 21:38:28.988502016 +0000 UTC m=+229.070397331
# Command: skyramp generate contract rest http://localhost:4200/api/impact/flows/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa/dependencies/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_flow_dependency_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"upstream_flow_id":"aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa","downstream_flow_id":"bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb","dependency_type":"triggers"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/impact/flows/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa/dependencies/ POST
def test_dependencies_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    dependencies_POST_request_body = r'''{
        "dependency_type": "triggers",
        "downstream_flow_id": "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
        "upstream_flow_id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"
    }'''

    # Execute Request
    dependencies_POST_response = client.send_request(
        url=URL,
        path="/api/impact/flows/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa/dependencies/",
        method="POST",
        body=dependencies_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(dependencies_POST_response, "20x")
    assert "id" in dependencies_POST_response.json()
    assert "upstream_flow_id" in dependencies_POST_response.json()
    assert "downstream_flow_id" in dependencies_POST_response.json()
    assert "dependency_type" in dependencies_POST_response.json()


if __name__ == "__main__":
    test_dependencies_post()
