# Generated by Skyramp v1.3.13 on 2026-03-16 21:35:01.420239928 +0000 UTC m=+140.889344959
# Command: skyramp generate contract rest http://127.0.0.1:4200/api/flow-validation/flows/11111111-1111-1111-1111-111111111111/graph-analysis/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_flow_graph_analysis_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

# contract test for /api/flow-validation/flows/11111111-1111-1111-1111-111111111111/graph-analysis/ GET
def test_graph_analysis_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    graph-analysis_GET_response = client.send_request(
        url=URL,
        path="/api/flow-validation/flows/11111111-1111-1111-1111-111111111111/graph-analysis/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(graph-analysis_GET_response, "20x")


if __name__ == "__main__":
    test_graph_analysis_get()
