# Generated by Skyramp v1.3.13 on 2026-03-20 13:56:34.367540664 +0000 UTC m=+198.422162662
# Command: skyramp generate contract rest http://localhost:4200/health/readiness \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_health_readiness_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-data {"ready":true,"checks":{"database":"ok","api":"ok"}} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /health/readiness GET
def test_readiness_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_readiness_GET_response_body = r'''{
        "checks": {
            "api": "ok",
            "database": "ok"
        },
        "ready": true
    }'''

    # Execute Request
    readiness_GET_response = client.send_request(
        url=URL,
        path="/health/readiness",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(readiness_GET_response, "20x")
    assert skyramp.check_schema(readiness_GET_response, expected_readiness_GET_response_body)
    assert skyramp.get_response_value(readiness_GET_response, "checks.api") is not None
    assert skyramp.get_response_value(readiness_GET_response, "checks.database") is not None
    assert skyramp.get_response_value(readiness_GET_response, "ready") is not None


if __name__ == "__main__":
    test_readiness_get()
