# Generated by Skyramp v1.3.13 on 2026-03-16 21:14:46.854438048 +0000 UTC m=+151.567582765
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_quota_lifecycle.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-quota-lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_id = "11111111-1111-1111-1111-111111111111"

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "labels": {},
        "name": "quota-test-flow-1234",
        "tags": []
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "flow_id": "11111111-1111-1111-1111-111111111111",
        "max_concurrent_runs": 5,
        "max_runs_per_day": 200,
        "max_runs_per_hour": 50,
        "quota_exceeded_action": "reject"
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/quotas/flows/{flows}/quota/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers,
        path_params={"flows": skyramp.get_response_value(endpoint_1_POST_response, "id")},
        data_override={"flow_id": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/quotas/flows/{flows}/quota/",
        method="GET",
        headers=headers,
        path_params={"flows": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200

    # Request Body
    endpoint_2_PATCH_request_body = r'''{
        "max_concurrent_runs": 10,
        "max_runs_per_hour": 100
    }'''
    
    # Execute Request
    endpoint_2_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/api/quotas/flows/{flows}/quota/",
        method="PATCH",
        body=endpoint_2_PATCH_request_body,
        headers=headers,
        path_params={"flows": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_2_PATCH_response.status_code == 200

    # Execute Request
    endpoint_2_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/quotas/flows/{flows}/quota/",
        method="DELETE",
        headers=headers,
        path_params={"flows": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_2_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
