# Generated by Skyramp v1.3.13 on 2026-03-19 14:22:33.562990531 +0000 UTC m=+166.813199383
# Command: skyramp generate fuzz rest http://localhost:4200/api/management/users \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_management_users_fuzz.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"name":"Alice Smith","email":"alice@example.com"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# fuzz test for /api/management/users POST
def test_users_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    users_POST_request_body = r'''{
      "name": "Alice Smith",
      "email": "alice@example.com"
    }'''
    
    # Fuzz strategies
    users_post_fuzzed_body = {
        "email": "0123456789",
        "name": "0123456789"
    }
    # Fuzz status codes
    expected_users_post_status_code = {
        "email": "40x",
        "name": "40x"
    }
    # Fuzz status codes for Null values
    expected_users_post_null_status_code = {
        "email": "40x",
        "name": "40x"
    }

    # Execute Request
    users_POST_response = client.send_request(
        url=URL,
        path="/api/management/users",
        method="POST",
        body=users_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(users_post_fuzzed_body):
        # Execute Request
        users_POST_response = client.send_request(
            url=URL,
            path="/api/management/users",
            method="POST",
            body=users_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(users_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_users_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(users_post_fuzzed_body, key) }'
        )

        # Execute Request
        users_POST_response = client.send_request(
            url=URL,
            path="/api/management/users",
            method="POST",
            body=users_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_users_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_users_post()
