# Generated by Skyramp v1.3.13 on 2026-03-16 18:49:45.433782621 +0000 UTC m=+115.189065493
# Command: skyramp generate fuzz rest http://localhost:4200/api/flow-costs/profiles/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_flow_cost_profile_fuzz.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"flow_id":"11111111-1111-1111-1111-111111111111","cost_per_second":0.01,"cost_per_task":0.05,"currency":"USD"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# fuzz test for /api/flow-costs/profiles/ POST
def test_profiles_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    profiles_POST_request_body = r'''{
      "flow_id": "11111111-1111-1111-1111-111111111111",
      "cost_per_second": 0.01,
      "cost_per_task": 0.05,
      "currency": "USD"
    }'''
    
    # Fuzz strategies
    profiles_post_fuzzed_body = {
        "cost_per_second": -10,
        "cost_per_task": -10,
        "currency": "0123456789",
        "flow_id": "0123456789"
    }
    # Fuzz status codes
    expected_profiles_post_status_code = {
        "cost_per_second": "40x",
        "cost_per_task": "40x",
        "currency": "40x",
        "flow_id": "40x"
    }
    # Fuzz status codes for Null values
    expected_profiles_post_null_status_code = {
        "cost_per_second": "40x",
        "cost_per_task": "40x",
        "currency": "40x",
        "flow_id": "40x"
    }

    # Execute Request
    profiles_POST_response = client.send_request(
        url=URL,
        path="/api/flow-costs/profiles/",
        method="POST",
        body=profiles_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(profiles_post_fuzzed_body):
        # Execute Request
        profiles_POST_response = client.send_request(
            url=URL,
            path="/api/flow-costs/profiles/",
            method="POST",
            body=profiles_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(profiles_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_profiles_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(profiles_post_fuzzed_body, key) }'
        )

        # Execute Request
        profiles_POST_response = client.send_request(
            url=URL,
            path="/api/flow-costs/profiles/",
            method="POST",
            body=profiles_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_profiles_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_profiles_post()
