# Generated by Skyramp v1.3.14 on 2026-03-20 17:38:11.753219575 +0000 UTC m=+259.654538710
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_cost_tracking_workflow.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-cost-tracking-workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_id = "7f8a9b2c-3d4e-5f6a-7b8c-9d0e1f2a3b4c"
    flow_run_id = "1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d"

    # Request Body
    endpoint_1_POST_request_body = r'''{}'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs-v2/profiles/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers,
        query_params={
            "cost_per_second": ["0.05"],
            "cost_per_task": ["0.1"],
            "currency": ["USD"],
            "flow_id": flow_id
        }
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    endpoint_2_POST_request_body = r'''{}'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs-v2/run-costs/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers,
        query_params={
            "execution_seconds": ["1250"],
            "flow_run_id": flow_run_id,
            "task_count": ["10"],
            "total_cost": ["12.5"]
        }
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201

    # Execute Request
    flow_run_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs-v2/run-costs/flow-run/{flow-run}",
        method="GET",
        headers=headers,
        path_params={"flow-run": skyramp.get_response_value(endpoint_2_POST_response, "flow_run_id")}
    )
    # Generated Assertions
    assert flow_run_GET_response.status_code == 200

    # Execute Request
    flow_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs-v2/history/flow/{flow}",
        method="GET",
        headers=headers,
        path_params={"flow": skyramp.get_response_value(endpoint_1_POST_response, "flow_id")}
    )
    # Generated Assertions
    assert flow_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
