# Generated by Skyramp v1.3.13 on 2026-03-16 22:03:02.157348681 +0000 UTC m=+249.330036876
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_quota_not_found_404.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_quota-not-found-404.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "labels": {},
        "name": "quota-404-test-flow-9999",
        "tags": []
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/quotas/flows/{flows}/quota/",
        method="GET",
        headers=headers,
        path_params={"flows": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 404

    # Execute Request
    endpoint_2_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/quotas/flows/{flows}/quota/",
        method="DELETE",
        headers=headers,
        path_params={"flows": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert endpoint_2_DELETE_response.status_code == 404


if __name__ == "__main__":
    test_integration()
