# Generated by Skyramp v1.3.13 on 2026-03-16 22:37:20.61202846 +0000 UTC m=+128.575422885
# Command: skyramp generate contract rest http://127.0.0.1:4200/api/flow-validation/flows/11111111-1111-1111-1111-111111111111/validate-graph/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_flow_validate_graph_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

# contract test for /api/flow-validation/flows/11111111-1111-1111-1111-111111111111/validate-graph/ POST
def test_validate_graph_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    validate-graph_POST_request_body = r'''{}'''

    # Execute Request
    validate-graph_POST_response = client.send_request(
        url=URL,
        path="/api/flow-validation/flows/11111111-1111-1111-1111-111111111111/validate-graph/",
        method="POST",
        body=validate-graph_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(validate-graph_POST_response, "20x")


if __name__ == "__main__":
    test_validate_graph_post()
