# Generated by Skyramp v1.3.13 on 2026-03-16 21:34:07.327644912 +0000 UTC m=+143.983707119
# Command: skyramp generate contract rest http://localhost:4200/api/checkpoints/flow-runs/00000000-0000-0000-0000-000000000001/checkpoints/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_checkpoints_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/checkpoints/flow-runs/00000000-0000-0000-0000-000000000001/checkpoints/ GET
def test_checkpoints_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    checkpoints_GET_response = client.send_request(
        url=URL,
        path="/api/checkpoints/flow-runs/00000000-0000-0000-0000-000000000001/checkpoints/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(checkpoints_GET_response, "20x")


if __name__ == "__main__":
    test_checkpoints_get()
