# Generated by Skyramp v1.3.13 on 2026-03-20 13:56:30.903565983 +0000 UTC m=+194.958187981
# Command: skyramp generate contract rest http://localhost:4200/health/status \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_health_status_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-data {"status":"healthy","version":"2.0.0","service":"prefect-server"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /health/status GET
def test_status_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_status_GET_response_body = r'''{
        "service": "prefect-server",
        "status": "healthy",
        "version": "2.0.0"
    }'''

    # Execute Request
    status_GET_response = client.send_request(
        url=URL,
        path="/health/status",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(status_GET_response, "20x")
    assert skyramp.check_schema(status_GET_response, expected_status_GET_response_body)
    assert skyramp.get_response_value(status_GET_response, "service") is not None
    assert skyramp.get_response_value(status_GET_response, "status") is not None
    assert skyramp.get_response_value(status_GET_response, "version") is not None


if __name__ == "__main__":
    test_status_get()
