# Generated by Skyramp v1.3.13 on 2026-03-16 22:20:23.648038643 +0000 UTC m=+182.099283159
# Command: skyramp generate contract rest http://localhost:4200/api/quotas/flows/11111111-1111-1111-1111-111111111111/quota/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_quota_get_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/quotas/flows/11111111-1111-1111-1111-111111111111/quota/ GET
def test_quota_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    quota_GET_response = client.send_request(
        url=URL,
        path="/api/quotas/flows/11111111-1111-1111-1111-111111111111/quota/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(quota_GET_response, "20x")


if __name__ == "__main__":
    test_quota_get()
