# Generated by Skyramp v1.3.13 on 2026-03-16 21:34:29.485005657 +0000 UTC m=+230.532139013
# Command: skyramp generate contract rest http://localhost:4200/api/traces/flow-runs/00000000-0000-0000-0000-000000000000/trace/00000000-0000-0000-0000-000000000001/spans/ \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_trace_spans_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 404 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/traces/flow-runs/00000000-0000-0000-0000-000000000000/trace/00000000-0000-0000-0000-000000000001/spans/ GET
def test_spans_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    spans_GET_response = client.send_request(
        url=URL,
        path="/api/traces/flow-runs/00000000-0000-0000-0000-000000000000/trace/00000000-0000-0000-0000-000000000001/spans/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert spans_GET_response.status_code == 404


if __name__ == "__main__":
    test_spans_get()
