# Generated by Skyramp v1.3.14 on 2026-03-20 18:31:00.811211926 +0000 UTC m=+98.842346898
# Command: skyramp generate contract rest http://localhost:4200/flow-quotas/usage/{flow_id} \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /flow-quotas/usage/{flow_id} GET
def test_usage_flow_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Execute Request
    usage_flow_id_GET_response = client.send_request(
        url=URL,
        path="/flow-quotas/usage/{flow_id}",
        method="GET",
        headers=headers,
        path_params={"flow_id": flow_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(usage_flow_id_GET_response, "20x")


if __name__ == "__main__":
    test_usage_flow_id_get()
