# Generated by Skyramp v1.3.14 on 2026-03-20 17:49:37.791563513 +0000 UTC m=+183.337096930
# Command: skyramp generate contract rest http://localhost:4200/api/flow-quotas/usage/{flow_id} \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--response-data {"flow_id":"3fa85f64-5717-4562-b3fc-2c963f66afa6","current_concurrent_runs":3,"runs_today":25,"limit_reached":false} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-quotas/usage/{flow_id} GET
def test_usage_flow_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Expected Response Body
    expected_usage_flow_id_GET_response_body = r'''{
        "current_concurrent_runs": 3,
        "flow_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "limit_reached": false,
        "runs_today": 25
    }'''

    # Execute Request
    usage_flow_id_GET_response = client.send_request(
        url=URL,
        path="/api/flow-quotas/usage/{flow_id}",
        method="GET",
        headers=headers,
        path_params={"flow_id": flow_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(usage_flow_id_GET_response, "20x")
    assert skyramp.check_schema(usage_flow_id_GET_response, expected_usage_flow_id_GET_response_body)
    assert skyramp.get_response_value(usage_flow_id_GET_response, "current_concurrent_runs") is not None
    assert skyramp.get_response_value(usage_flow_id_GET_response, "flow_id") is not None
    assert skyramp.get_response_value(usage_flow_id_GET_response, "limit_reached") is not None


if __name__ == "__main__":
    test_usage_flow_id_get()
