# Generated by Skyramp v1.3.14 on 2026-03-20 17:52:00.291493701 +0000 UTC m=+190.682440449
# Command: skyramp generate contract rest http://localhost:4200/api/task-retries/runs/{run_id}/usage \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params run_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--response-data {"run_id":"3fa85f64-5717-4562-b3fc-2c963f66afa6","total_retries":3,"budget_remaining":7,"tasks_retried":["task-1","task-3"]} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/task-retries/runs/{run_id}/usage GET
def test_usage_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    run_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Expected Response Body
    expected_usage_GET_response_body = r'''{
        "budget_remaining": 7,
        "run_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "tasks_retried": [
            "task-1",
            "task-3"
        ],
        "total_retries": 3
    }'''

    # Execute Request
    usage_GET_response = client.send_request(
        url=URL,
        path="/api/task-retries/runs/{run_id}/usage",
        method="GET",
        headers=headers,
        path_params={"run_id": run_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(usage_GET_response, "20x")
    assert skyramp.check_schema(usage_GET_response, expected_usage_GET_response_body)
    assert skyramp.get_response_value(usage_GET_response, "budget_remaining") is not None
    assert skyramp.get_response_value(usage_GET_response, "run_id") is not None
    assert skyramp.get_response_value(usage_GET_response, "tasks_retried.0") is not None


if __name__ == "__main__":
    test_usage_get()
