# Generated by Skyramp v1.3.14 on 2026-03-20 18:32:50.024497191 +0000 UTC m=+140.269920736
# Command: skyramp generate contract rest http://localhost:4200/api/task-validation/validate \
# 		--api-schema http://localhost:4200/api/openapi.json \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--query-params task_id=task-abc-123 \
# 		--request-data {"result":"processed_successfully"} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/task-validation/validate POST
def test_validate_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    validate_POST_request_body = r'''{
        "result": "processed_successfully"
    }'''

    # Expected Response Body
    expected_validate_POST_response_body = r'''"string"'''

    # Execute Request
    validate_POST_response = client.send_request(
        url=URL,
        path="/api/task-validation/validate",
        method="POST",
        body=validate_POST_request_body,
        headers=headers,
        query_params={"task_id": "task-abc-123"}
    )

    # Generated Assertions
    assert validate_POST_response.status_code == 200
    assert skyramp.check_schema(validate_POST_response, expected_validate_POST_response_body)


if __name__ == "__main__":
    test_validate_post()
