# Generated by Skyramp v1.3.14 on 2026-03-20 17:29:57.007181105 +0000 UTC m=+107.340159316
# Command: skyramp generate contract rest http://localhost:4200/api/flow-dependencies/flows/{flow_id}/validate \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params flow_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--provider \
# 		--request-data {"flow_id":"3fa85f64-5717-4562-b3fc-2c963f66afa6"} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-dependencies/flows/{flow_id}/validate POST
def test_validate_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    validate_POST_request_body = r'''{
        "flow_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    }'''

    # Execute Request
    validate_POST_response = client.send_request(
        url=URL,
        path="/api/flow-dependencies/flows/{flow_id}/validate",
        method="POST",
        body=validate_POST_request_body,
        headers=headers,
        path_params={"flow_id": flow_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(validate_POST_response, "20x")


if __name__ == "__main__":
    test_validate_post()
