# Generated by Skyramp v1.3.14 on 2026-03-20 17:49:43.649123667 +0000 UTC m=+135.734963182
# Command: skyramp generate contract rest http://localhost:4200/api/task-validation/validate \
# 		--auth-header Authorization \
# 		--consumer \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--request-data {"task_id":"3fa85f64-5717-4562-b3fc-2c963f66afa6","output_data":{"result":"success","value":42}} \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp
from skyramp import MockV2


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/task-validation/validate POST
def test_validate_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    validate_POST_request_body = r'''{
        "output_data": {
            "result": "success",
            "value": 42
        },
        "task_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    }'''

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/task-validation/validate",
        method="POST",
        status_code=200,
        request_body=validate_POST_request_body
    )
    client.apply_mock(mock)

    # Execute Request
    validate_POST_response = client.send_request(
        url=URL,
        path="/api/task-validation/validate",
        method="POST",
        body=validate_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(validate_POST_response, "20x")

    client.remove_all_mocks()


if __name__ == "__main__":
    test_validate_post()
