# Generated by Skyramp v1.3.14 on 2026-03-20 17:49:39.642412413 +0000 UTC m=+131.728251938
# Command: skyramp generate fuzz rest http://localhost:4200/api/task-validation/validate \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--request-data {"task_id":"3fa85f64-5717-4562-b3fc-2c963f66afa6","output_data":{"result":"success","value":42}} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# fuzz test for /api/task-validation/validate POST
def test_validate_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    validate_POST_request_body = r'''{
      "task_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "output_data": {
        "result": "success",
        "value": 42
      }
    }'''
    
    # Fuzz strategies
    validate_post_fuzzed_body = {
        "output_data": {
            "result": "0123456789",
            "value": -10
        },
        "task_id": "0123456789"
    }
    # Fuzz status codes
    expected_validate_post_status_code = {
        "output_data": {
            "result": "40x",
            "value": "40x"
        },
        "task_id": "40x"
    }
    # Fuzz status codes for Null values
    expected_validate_post_null_status_code = {
        "output_data": {
            "result": "40x",
            "value": "40x"
        },
        "task_id": "40x"
    }

    # Execute Request
    validate_POST_response = client.send_request(
        url=URL,
        path="/api/task-validation/validate",
        method="POST",
        body=validate_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(validate_post_fuzzed_body):
        # Execute Request
        validate_POST_response = client.send_request(
            url=URL,
            path="/api/task-validation/validate",
            method="POST",
            body=validate_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(validate_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_validate_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(validate_post_fuzzed_body, key) }'
        )

        # Execute Request
        validate_POST_response = client.send_request(
            url=URL,
            path="/api/task-validation/validate",
            method="POST",
            body=validate_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_validate_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_validate_post()
