# Generated by Skyramp v1.3.13 on 2026-03-19 11:49:07.243049049 +0000 UTC m=+77.907127947
# Command: skyramp generate contract rest http://localhost:4200/api/config-test/precedence \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/workflow-tests \
# 		--overwrite \
# 		--provider \
# 		--response-data {"test":"SKYR-3646","check":"config_precedence","expected_directory":"workflow-tests"} \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/config-test/precedence GET
def test_precedence_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_precedence_GET_response_body = r'''{
        "check": "config_precedence",
        "expected_directory": "workflow-tests",
        "test": "SKYR-3646"
    }'''

    # Execute Request
    precedence_GET_response = client.send_request(
        url=URL,
        path="/api/config-test/precedence",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert precedence_GET_response.status_code == 200
    assert skyramp.check_schema(precedence_GET_response, expected_precedence_GET_response_body)
    assert skyramp.get_response_value(precedence_GET_response, "check") is not None
    assert skyramp.get_response_value(precedence_GET_response, "expected_directory") is not None
    assert skyramp.get_response_value(precedence_GET_response, "test") is not None


if __name__ == "__main__":
    test_precedence_get()
