# Generated by Skyramp v1.3.13 on 2026-03-19 11:49:09.145872825 +0000 UTC m=+79.809951733
# Command: skyramp generate fuzz rest http://localhost:4200/api/config-test/precedence \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/workflow-tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# fuzz test for /api/config-test/precedence GET
def test_precedence_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    precedence_GET_response = client.send_request(
        url=URL,
        path="/api/config-test/precedence",
        method="GET",
        headers=headers,
        expected_code="20x"
    )

    assert client.is_success()


if __name__ == "__main__":
    test_precedence_get()
