# Generated by Skyramp v1.3.13 on 2026-03-19 12:27:48.986305364 +0000 UTC m=+62.405530531
# Command: skyramp generate contract rest http://localhost:4200/api/config-test/workspace-only \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/workspace-tests \
# 		--overwrite \
# 		--provider \
# 		--response-data {"test":"SKYR-3646-workspace-only","workspace_outputDir":"workspace-tests","workflow_test_directory":"none","expected_location":"workspace-tests"} \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/config-test/workspace-only GET
def test_workspace_only_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_workspace_only_GET_response_body = r'''{
        "expected_location": "workspace-tests",
        "test": "SKYR-3646-workspace-only",
        "workflow_test_directory": "none",
        "workspace_outputDir": "workspace-tests"
    }'''

    # Execute Request
    workspace_only_GET_response = client.send_request(
        url=URL,
        path="/api/config-test/workspace-only",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert workspace_only_GET_response.status_code == 200
    assert skyramp.check_schema(workspace_only_GET_response, expected_workspace_only_GET_response_body)
    assert skyramp.get_response_value(workspace_only_GET_response, "expected_location") is not None
    assert skyramp.get_response_value(workspace_only_GET_response, "test") is not None
    assert skyramp.get_response_value(workspace_only_GET_response, "workflow_test_directory") is not None


if __name__ == "__main__":
    test_workspace_only_get()
